### ISSUE TITLE
Add setup instructions for the AWS collector on Elastic Beanstalk

### ISSUE THREAD

**Issue by willarmiros** [aws-observability/aws-otel-collector#109]
We currently provide step-by-step instructions for running the collector on ECS, EKS, and EC2. We should also provide documentation and a sample YAML file for running the collector on Elastic Beanstalk. The below docs describe how to run custom software on the instances for a beanstalk environment using Linux or Windows, and the structure of the yaml file we'd provide to customers.

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#linux-commands
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-windows-ec2.html#windows-commands

A couple caveats:
1. customers *do* need to enable the X-Ray Daemon in their environment for the EB resource detector to collect and record metadata (except in the docker platforms where it's not available).
2. Beanstalk supports a [multi-container docker platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_ecs.html) that uses ECS under the hood, but is configured with a `dockerrun.aws.json` file instead of a task definition (madness I know) so we should also include a sample for that too.

**Comment by mxiamxia** [comment]
Hi @willarmiros , can you please own this item?

**Comment by NtFreX** [comment]
I deploy with the aws extension for visual studio and got a simple version working with the following config. XRay does not work though. I get the following error.

> {"kind": "exporter", "name": "awsxray", "error": "Permanent error: AccessDeniedException: \n\tstatus code: 403, request id: 9c9c8820-29d2-4527-9de7-d9509fee46ff"}

The config basically  copied from the linux ec2 instructions. I added `rpm -qa | grep -qw 'aws-otel-collector' ||` in front of the install command because when deploying multiple times to the same machine I got an error saying that the package already exists.
https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/linux-rpm-demo.md

`.ebextensions/https-instance-single.config`
```
commands:
  01_download_otel_collector:
    command: "wget https://aws-otel-collector.s3.amazonaws.com/amazon_linux/amd64/latest/aws-otel-collector.rpm"
  02_install_otel_collector:
    command: "rpm -qa | grep -qw 'aws-otel-collector' || sudo rpm -Uvh  ./aws-otel-collector.rpm"
  03_stop_otel_collector:
    command: "sudo /opt/aws/aws-otel-collector/bin/aws-otel-collector-ctl  -a stop"
  04_run_otel_collector:
    command: "sudo /opt/aws/aws-otel-collector/bin/aws-otel-collector-ctl -c /var/app/current/otel_config.yaml -a start"
```

In this file I removed the awsxray receiver as it is already created by the ebs deployment and my publishers are using the grpc format. I also removed the http receiver because I don't need it. Also the batch processor for traces did not work for me. Other then that it's almost a copy of https://github.com/aws-observability/aws-otel-collector/blob/main/config.yaml.
`otel_config.yaml`
```
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch/metrics:
    timeout: 60s

exporters:
  logging:
  awsxray:
  awsemf:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awsemf]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging]

  extensions: [health_check]
```

To make this all work I also added the following policy to the EBS execution role.

```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Action": [
				"logs:PutLogEvents",
				"logs:CreateLogGroup",
				"logs:CreateLogStream",
				"logs:DescribeLogStreams",
				"logs:DescribeLogGroups",
				"ssm:GetParameters"
			],
			"Resource": "*"
		}
	]
}
```

To fix the XRay auth error I tried adding 'xray:*' to the allowed actions but this did not work.
