### ISSUE TITLE
How to change the default log level from INFO to ERROR for ADOT running as sidecar in fargate?

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#1099]
How to change the default log level from INFO to ERROR for ADOT running as sidecar in fargate?

OTEL side car config value is: /etc/ecs/container-insights/otel-task-metrics-config.yaml.  It is the standard config from adot aws git repo. Here is the complete url: https://github.com/aws-observability/aws-otel-collector/blob/main/config/ecs/container-insights/otel-task-metrics-config.yaml

**Comment by bryan-aguilar** [comment]
```
```

**Comment by bryan-aguilar** [comment]
You would need to update your service definition as such 
```
service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      processors: [batch/traces]
      exporters: [awsxray]
    metrics/application:
      receivers: [otlp, statsd]
      processors: [batch/metrics]
      exporters: [awsemf/application]
    metrics/performance:
      receivers: [awsecscontainermetrics ]
      processors: [filter, metricstransform, resource]
      exporters: [ awsemf/performance ]

  extensions: [health_check]
  telemetry:
    logs:
      level: error
```
