### ISSUE TITLE
Allow passing feature flags to Prometheus receiver

### ISSUE THREAD

**Issue by dnutels** [aws-observability/aws-otel-collector#1173]
**Is your feature request related to a problem? Please describe.**

Ability to enable exemplars, currently an experimental feature, for the Prometheus receiver. For "vanilla" Prometheus
it is done via `--enable-feature=exemplar-storage`.

**Describe the solution you'd like**

Looking for a way to pass Prometheus flags to the ADOT collector.

Reason — exemplars are behind a feature flag, that for “regular” Prometheus would be passed (using docker compose as an example) like this:

```
services:
  ...
  prometheus:
    image: prom/prometheus:latest
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=exemplar-storage'
    volumes:
      - ${PWD}/infra/prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
```

Then prometheus would scrape OpenMetrics format with exemplars… equivalent to:

```
curl example.com:3000/metrics -H "Accept: application/openmetrics-text"
```
**Describe alternatives you've considered**

OTEL collector or N/A

**Additional context**

N/A
