### ISSUE TITLE
relabel_configs replacement regex failing

### ISSUE THREAD

**Issue by lkysow** [aws-observability/aws-otel-collector#1201]
```
```

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**Environment**
Describe any aspect of your environment relevant to the problem. 
If this is related to a deployment of the ADOT Collector please
provide your Collector config file. 

**Additional context**
```

```

**Comment by lkysow** [comment]
I've confirmed that this config works with vanilla prometheus.

**Comment by bryan-aguilar** [comment]
What version of the ADOT Collector is being used?

**Comment by bryan-aguilar** [comment]
I can't say for sure, I haven't been able to test it yet but after poking through the [example docs](https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-kubernetes.yml) is it possible that the single quotes are causing issues?

**Comment by lkysow** [comment]
I'm building the Dockerfile from `latest`: `public.ecr.aws/aws-observability/aws-otel-collector:latest`.

> is it possible that the single quotes are causing issues?

No, I've tested this with and without single quotes. And the same config works with regular prometheus (https://github.com/lkysow/containers-couch-consul-ecs/blob/main/prometheus.tf#L159-L174 - the extra escape chars there are because it's embedded in tf).

I'm happy to jump on a zoom or something to help repro. You can DM me: https://twitter.com/lkysow

**Comment by PaurushGarg** [comment]
Prometheus configuration requires the use of additional '$' operator where the configuration is interpreted as environment variables. So, here the replacement configuration should be as follows: `replacement: '$${1}:9102'`.

**Comment by lkysow** [comment]
Nice find! I'll try it and report back.

**Comment by lkysow** [comment]
🎉 it works, thanks so much @PaurushGarg !

My config for posterity:

```yaml
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
        - job_name: consul
          metrics_path: /metrics
          consul_sd_configs:
          - server: '<address>:8500'
          relabel_configs:
          - source_labels:
            - __meta_consul_tagged_address_lan
            regex: '(.*)'
            replacement: '$${1}:9102'
            target_label: '__address__'
            action: 'replace'
  awsecscontainermetrics:
    collection_interval: 10s
processors:
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.utilized
          - ecs.task.memory.reserved
          - ecs.task.cpu.utilized
          - ecs.task.cpu.reserved
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
exporters:
  awsprometheusremotewrite:
    endpoint: <ep>
    aws_auth:
      region: us-east-1
      service: aps
  logging:
    loglevel: info
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
service:
  telemetry:
    logs:
      level: debug
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging, awsprometheusremotewrite]
    metrics/ecs:
      receivers: [awsecscontainermetrics]
      processors: [filter]
      exporters: [logging, awsprometheusremotewrite]

```
