### ISSUE TITLE
Missing metric dimensions in EMF when using opentelemetry exporter-metrics-otlp-grpc

### ISSUE THREAD

**Issue by Rikkedi** [aws-observability/aws-otel-collector#1216]
**Describe the bug**
I'm adding instrumentation to a NestJS service (running in ECS Fargate) using the OTLPMetricExporter from '@opentelemetry/exporter-metrics-otlp-grpc' and then running awsemf exporter as a sidecar to pipe these to CloudWatch in Embedded Metrics Format. However, I can't get any of my metric attributes to show up as dimensions in emf, not in the log awsemf debug logs or in the generated metrics stream.

**Steps to reproduce**
Sample code for the instrumentation
```
import { OTLPMetricExporter } from '@opentelemetry/exporter-metrics-otlp-grpc';
import { Resource } from '@opentelemetry/resources';
import { ConsoleMetricExporter, Meter, MeterProvider, MetricExporter } from '@opentelemetry/sdk-metrics-base';

const exporter = new OTLPMetricExporter({ url: 'grpc://localhost:4317' })
const meterProvider: MeterProvider = new MeterProvider({
      resource: Resource.default().merge(
        new Resource({
          [SemanticResourceAttributes.SERVICE_NAME]: 'test-service'
        })
      ),
      exporter: exporter,
      interval: 5000
    });
const meter = meterProvider.getMeter('some-name');
const counter = meter.createCounter('http_requests_total', {
      description: `Total count of HTTP requests received`,
      component: 'http',
      valueType: 1,
      unit: 'Count'
    });
counter.add(1, {http_route: 'test', http_method: 'get', http_controller: 'testController', http_controller_method: 'getTest'});
```

**What did you expect to see?**
I expect to see metrics in EMF like the following
```
{
    "OTelLib": "some-name",
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "MyNamespace",
                "Dimensions": [
                    [
                        "OTelLib",
                        "service.name",
                        "http_route",
                        "http_method",
                        "http_controller",
                        "http_controller_method",
                        "telemetry.sdk.version"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "http_requests_total",
                        "Unit": "Count"
                    }
                ]
            }
        ],
        "Timestamp": 1652209141514
    },
    "service.name": "test-service",
    "http_request_failures": 1,
    "http_route": "test",
    "http_method": "get",
    "http_controller": "testController",
    "http_controller_method": "getTest",
    "telemetry.sdk.version": "1.0.1"
}
```

**What did you see instead?**
Instead, I get the metrics that come through the Resource object, but none of my custom attributes.
```
{
    "OTelLib": "some-name",
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "MyNamespace",
                "Dimensions": [
                    [
                        "OTelLib",
                        "service.name",
                        "telemetry.sdk.version"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "http_requests_total",
                        "Unit": "Count"
                    }
                ]
            }
        ],
        "Timestamp": 1652209141514
    },
    "service.name": "test-service",
    "telemetry.sdk.version": "1.0.1"
}
```

**Environment**
The collector runs as a sidecar to an ECS Fargate task.
config.yaml
```
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch/metrics:
    timeout: 60s
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500
  resource:
    attributes:
      - key: telemetry.sdk.language
        action: delete
      - key: telemetry.sdk.name
        action: delete

exporters:
  logging:
    loglevel: debug
  awsemf:
    namespace: 'MyNamespace'
    log_group_name: 'MyLogGroup'
    dimension_rollup_option: NoDimensionRollup
    resource_to_telemetry_conversion:
      enabled: true
    # I've tried with and without `attributes` in this setting.
    # parse_json_encoded_attr_values: [attributes]

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch/metrics]
      exporters: [logging, awsemf]

  extensions: [health_check]
```
I'm mounting the config to the container by generating my own image from `aws-otel-collector`
```
#Dockerfile
FROM amazon/aws-otel-collector

COPY config.yaml /workspace/config/otel-awsemf-config.yaml

CMD ["--config=/workspace/config/otel-awsemf-config.yaml"]
```

Node environment:
```
   node: 16.13.0
    "@opentelemetry/exporter-metrics-otlp-grpc": "0.27.0",
    "@opentelemetry/sdk-metrics-base": "0.27.0",
```

**Additional context**
Running the otlp-grpc exporter with debug logging, I can see the attributes being sent:
```
items to be sent [
  {
    descriptor: {
      name: 'http_requests_total',
      description: 'Total count of HTTP requests received',
      unit: 'Count',
      metricKind: 0,
      valueType: 1
    },
    attributes: {
      http_route: 'test',
      http_method: 'GET',
      http_controller: 'testController',
      http_controller_method: 'getTest'
    },
    aggregator: SumAggregator { kind: 0, _current: 1, _lastUpdateTime: [Array] },
    aggregationTemporality: 2,
    resource: Resource { attributes: [Object] },
    instrumentationLibrary: { name: 'some-name', version: undefined, schemaUrl: undefined }
  }
]
```

**Comment by dnutels** [comment]
Same issue with just:

```
receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  
  processors:
    batch/metrics:
      timeout: 1s
      send_batch_size: 50
  
  exporters:
    logging/metrics:
      loglevel: debug
  
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch/metrics]
        exporters: [logging/metrics]
  
```
