### ISSUE TITLE
Insufficient Kubernetes RBAC permissions in EKS Fargate Container Insights deployment template?

### ISSUE THREAD

**Issue by tatusl** [aws-observability/aws-otel-collector#1231]
**Describe the question**

It seems that adot-collector tries to get `aws-auth` ConfigMap in `kube-system` namespace to detect if the runtime is AWS EKS and it fails if the sufficient Kubernetes RBAC permissions are not added: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.51.0/processor/resourcedetectionprocessor/internal/aws/eks/detector.go#L86

See the log output with and without the RBAC permissions in the next section.

Is omitting these permissions in deployment template (https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/otel-fargate-container-insights.yaml) intentional?

**Steps to reproduce if your question is related to an action**

Without adding RBAC permissions to `aws-auth` ConfigMap, adot-collector logs the following warning and info during startup:

```
2022-05-16T10:34:25.807Z        warn    internal/resourcedetection.go:130       failed to detect resource    {"kind": "processor", "name": "resourcedetection", "error": "isEks() error retrieving auth configmap: failed to retrieve ConfigMap kube-system/aws-auth: configmaps \"aws-auth\" is forbidden: User \"system:serviceaccount:fargate-container-insights:adot-collector\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""}
2022-05-16T10:34:25.807Z        info    internal/resourcedetection.go:138       detected resource information{"kind": "processor", "name": "resourcedetection", "resource": {"ClusterName":"eksv2-bootstrap-test"}}
```

Whereas when `adot-collector` service account has the sufficient Kubernetes RBAC permissions to get `aws-auth` ConfigMap, the log output is the following:

```
2022-05-16T10:57:20.160Z        info    internal/resourcedetection.go:125       began detecting resource information  {"kind": "processor", "name": "resourcedetection"}
2022-05-16T10:57:20.175Z        info    internal/resourcedetection.go:138       detected resource information{"kind": "processor", "name": "resourcedetection", "resource": {"ClusterName":"eksv2-bootstrap-test","cloud.platform":"aws_eks","cloud.provider":"aws"}}
```

**What did you expect to see?**

I expect that adot-collector starts without warnings and runtime detection successfully detects AWS EKS.

**Environment**

adot-collector Docker image tag: `v0.17.0`

**Additional context**

I'm happy to contribute PR to EKS Fargate Containers Insights deployment template if this needs to be fixed.

**Comment by Aneurysm9** [comment]
Apologies for the disruption.  A change was made to the permissions for that deployment template as part of the upcoming `v0.18.0` release that  inadvertently affected more than it should have.  Can you confirm that the template currently on `HEAD` works for you?  Thanks.

**Comment by tatusl** [comment]
No worries. In fact, we checked the deployment template in the `main` branch. In addition, it seems that the only difference in [otel-fargate-container-insights](https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/otel-fargate-container-insights.yaml) file between the tag `v0.17.0` and `HEAD` in `main` branch seems to be the container image. So, the template in `HEAD` does not solve the issue.

For the context, here are the additional Kubernetes RBAC objects we locally added to fix the issue:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-aws-auth-configmap
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resourceNames:
  - aws-auth
  resources:
  - configmaps
  verbs:
  - get
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adotcol-get-aws-auth-configmap
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-aws-auth-configmap
subjects:
- kind: ServiceAccount
  name: adot-collector
  namespace: fargate-container-insights
```
