### ISSUE TITLE
ECS container.cpu.utilized metric unit claification

### ISSUE THREAD

**Issue by tomiszili** [aws-observability/aws-otel-collector#1368]
Hello!

What is the unit of the ECS container.cpu.utilized metric?
Please help me to understand what is the unit of the container.cpu.utilized metric, because it does not align with the CPUUtilization of the EC2 instance.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/54439475/180401507-12784235-5d6e-4221-b5c8-61cb99bc539e.png">

**Comment by imishchuk-carbon** [comment]
Hello, team.

We've been trying to figure out how `container.cpu.utilized` metric is calculated, but no luck.

Platform AWS ECS (Fargate or EC2, observed on both capacity providers)
ADOT version: `v0.22.0`

We have few observations, shared below:

Initially, we set CPU value on Task level only, leaving container level CPU at `0`

```
{
    ...
    "containerDefinitions": [
      {
        "cpu": 0,
        "name": "app"
      }
    ],
    
    "requiresCompatibilities": [
      "FARGATE"
    ],
    "cpu": "8192",
    ...
}
```

Container level CPU value of `0` is getting converted to `2` in background to be passed to `docker run --cpu-shares`. Explanation of this behavior is [here](https://github.com/corretto/corretto-8/issues/191#issuecomment-567772909) and [here](https://github.com/aws/amazon-ecs-agent/issues/1735)

This can be confirmed by graphing metric `container.cpu.reserved` for Task that has container level CPU set to `0`
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/100925121/198280750-0dd605a6-fa78-40e6-88c9-a5051cdd17f8.png">

And in that case `container.cpu.utilized` looks sane
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/100925121/198281175-211bf18b-6712-4b7f-a423-d577ebc52e7b.png">

Next, we set container level CPU to non-zero value like

```
{
    ...
    "containerDefinitions": [
      {
        "cpu": 7168,
        "name": "app"
      }
    ],
    
    "requiresCompatibilities": [
      "FARGATE"
    ],
    "cpu": "8192",
    ...
}
```

This is correctly reflected in `container.cpu.reserved` metric
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/100925121/198281689-a68717dd-8b89-4769-a948-899fce21c1d1.png">

But `container.cpu.utilized` gets messed up
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/100925121/198281954-0c7199eb-c71a-4549-a3a7-c6d98da90e6c.png">

Questions:
* How is `container.cpu.utilized` related to `container.cpu.reserved`?
* Which CloudWatch metrics are used for `container.cpu.utilized`?

Thank you.

**Comment by bryan-aguilar** [comment]
@imishchuk-carbon can you share the collector config you are using?

**Comment by imishchuk-carbon** [comment]
Hey @bryan-aguilar 
Thanks for looking into this.
Config below

```
extensions:
  health_check:
  sigv4auth:
    region: "us-east-1"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp
  awsecscontainermetrics:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-envoy-eg
          scrape_interval: 5s
          metrics_path: /stats/prometheus
          static_configs:
            - targets: ["localhost:9901"]
              labels:
                __ecs_container_metadata_uri: ${ECS_CONTAINER_METADATA_URI}
          relabel_configs:
            - source_labels: [__ecs_container_metadata_uri]
              target_label: ecs_task_id
              regex: '.*?/([a-z0-9]+)-\d+$'
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 20
    spike_limit_percentage: 15
  batch/traces:
    timeout: 5s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s
  resourcedetection:
    detectors:
      - env
      - system
      - ecs
      - ec2

exporters:
  otlphttp:
    endpoint: "${OTEL_COLLECTOR_ENDPOINT}"
  awsemf:
    namespace: ECS/AWSOTel/Application
    log_group_name: '/aws/ecs/application/metrics'
    region: "${OTEL_EXPORT_AMP_REGION}"
  # AWS Managed Prometheus Collector configuration
  prometheusremotewrite:
    endpoint: "${OTEL_EXPORTER_AMP_ENDPOINT}"
    auth:
      authenticator: sigv4auth
    resource_to_telemetry_conversion:
      enabled: true
    remote_write_queue:
      enabled: true
      num_consumers: 1
      queue_size: 5000
  logging:
    loglevel: debug


service:
  pipelines:
    traces:
      receivers: [otlp, awsxray]
      processors: [memory_limiter, resourcedetection, batch/traces]
      exporters: [otlphttp]
    metrics/application:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch/metrics]
      exporters: [prometheusremotewrite]
    metrics/envoy:
      receivers: [prometheus]
      processors: [memory_limiter, batch/metrics]
      exporters: [prometheusremotewrite]
    metrics:
      receivers: [awsecscontainermetrics]
      processors: [memory_limiter, batch/metrics]
      exporters: [otlphttp]

  extensions: [sigv4auth,health_check]
```
