### ISSUE TITLE
Unable to scrape cAdvisor after upgrade to v0.19.0

### ISSUE THREAD

**Issue by alexandrututunaru** [aws-observability/aws-otel-collector#1380]
Hello,

I managed to successfully export Kubernetes cAdvisor metrics to Prometheus using the image for release v0.18.0 (i.e. public.ecr.aws/aws-observability/aws-otel-collector:v0.18.0). Today I tried upgrading to v0.19.0 and it no longer works. I see entries of this type in the container logs:

2022-07-25T10:05:32.114Z	warn	internal/otlp_metricsbuilder.go:164	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_timestamp": 1658743531969, "target_labels": "map[__name__:up instance:ip-10-99-12-16.eu-west-1.compute.internal job:kubernetes-cadvisor]"}

My Collector config file looks like

```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 1m
        scrape_timeout: 55s
      scrape_configs:
      - job_name: 'kubernetes-cadvisor'
        sample_limit: 10000
        # Default to scraping over https. If required, just disable this or change to
        # `http`.
        scheme: https
        metrics_path: /metrics/cadvisor

        kubernetes_sd_configs:
        - role: node
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        metric_relabel_configs:
        - action: labeldrop
          regex: id|name
      - job_name: 'kube-state-metrics'
        static_configs:
        - targets: [ 0.0.0.0:8080 ]

exporters:
  prometheusremotewrite:
    endpoint: ${amp_write_endpoint}
    external_labels:
      account: ${account_name}
    auth:
      authenticator: sigv4auth

extensions:
  sigv4auth:
    assume_role:
      arn: ${amp_ingest_role_arn}

service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [prometheusremotewrite]
```

As you see, I also export metrics for kube-state-metrics and that still works in release v0.19.0, as it did in v0.18.0
