### ISSUE TITLE
Issue while receiving service name with ecscontainermetric receiver.

### ISSUE THREAD

**Issue by mohit-bureau** [aws-observability/aws-otel-collector#1382]
The adot collector is deployed as a sidecar in an ecs task in fargate. The receiver is able to get the metrics but  `"aws.ecs.service.name": "undefined"` is undefined.

Config Yaml File:

```
receivers:
  awsecscontainermetrics:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200
  otlp:
    endpoint: ENDPOINT
    headers:
      api-key: SENSITIVE

service:
  pipelines:
      metrics:
          receivers: [awsecscontainermetrics]
          exporters: [otlp, logging]
```

event:
```
  {
      "events": [
        {
          "aws.ecs.cluster.name": "ecs-clstr",
          "aws.ecs.launchtype": "fargate",
          "aws.ecs.service.name": "undefined",
          "aws.ecs.task.arn": "arn:aws:ecs:ap-south-1:99999999999:task/ecs-clstr/51caeeaf12a74f86bac677df6df3c24b",
          "aws.ecs.task.family": "sample-app",
          "aws.ecs.task.id": "51caeeaf12a74f86bac677df6df3c24b",
          "aws.ecs.task.known_status": "RUNNING",
          "aws.ecs.task.launch_type": "FARGATE",
          "aws.ecs.task.pull_started_at": "2022-07-20T06:38:06.172986773Z",
          "aws.ecs.task.pull_stopped_at": "2022-07-20T06:38:17.242745615Z",
          "aws.ecs.task.revision": "110",
          "aws.ecs.task.version": "110",
          "cloud.account.id": "99999999999",
          "cloud.availability_zone": "ap-south-1b",
          "cloud.region": "ap-south-1",
          "ecs.task.memory.utilized": {
            "type": "gauge",
            "count": 1,
            "sum": 55,
            "min": 55,
            "max": 55,
            "latest": 55
          },
          "instrumentation.provider": "opentelemetry",
          "metricName": "ecs.task.memory.utilized",
          "newrelic.source": "api.metrics.otlp",
          "otel.library.name": "",
          "otel.library.version": "",
          "timestamp": 1658394321523,
          "unit": "Megabytes"
        }
```

Log:
```
2022-07-20T12:08:41.529+05:30 | -> aws.ecs.service.name: STRING(undefined)
-- | --
  | 2022-07-20T12:08:41.530+05:30 | -> aws.ecs.service.name: STRING(undefined)
  | 2022-07-20T12:08:41.530+05:30 | -> aws.ecs.service.name: STRING(undefined)
  | 2022-07-20T12:08:41.531+05:30 | -> aws.ecs.service.name: STRING(undefined)
  | 2022-07-20T12:09:01.525+05:30 | -> aws.ecs.service.name: STRING(undefined)
  | 2022-07-20T12:09:01.525+05:30 | -> aws.ecs.service.name: STRING(undefined)
```
