### ISSUE TITLE
stream was reset: NO_ERROR when sending metrics from java agent

### ISSUE THREAD

**Issue by alex88** [aws-observability/aws-otel-collector#1535]
**Describe the bug**
I'm getting
```
ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: stream was reset: NO_ERROR
```
from the [java agent](https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr).
I still see the traces in XRay though.

**Steps to reproduce**
Install collector, run a sample java app with the agent installed with default settings

**What did you expect to see?**
No errors on the java agent

**What did you see instead?**
The error above

**Environment**
This is the config file:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50

exporters:
  awsxray:
  logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [awsxray,logging]
```

**Additional context**
AWS OTel Collector version: v0.20.1
AWS eks adot operator v0.56.0-eksbuild.2 (0.58 is broken because of [this](https://github.com/open-telemetry/opentelemetry-operator/issues/1098) issue)
