### ISSUE TITLE
How to use env variable (array of dictionaries) in AOT_CONFIG_CONTENT

### ISSUE THREAD

**Issue by jangaraj** [aws-observability/aws-otel-collector#1550]
Problem is that my  `AOT_CONFIG_CONTENT` is huge and I can't store it in single SSM parameter (4kB limit). So I would like to use 2 parameters and then use one in AOT_CONFIG_CONTENT. I would like to use 2 parameters - exposed as env variables in my ECS task definition. I use these env variables and docker run command for local testing:

```
# this variable will be very huge array of dictionaries (~4kB)
export SERVICE_FILTERS=$(cat <<EOF
- value: service-1
  exporters: otlphttp
- value: service-2
  exporters: otlphttp
EOF
)

export AOT_CONFIG_CONTENT=$(cat <<EOF
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp:
    endpoint: https://my-collector.com
  logging:
    loglevel: debug

processors:
  routing:
    from_attribute: service.name
    attribute_source: resource
    default_exporters:
    - logging
    table:
    \${SERVICE_FILTERS}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [routing]
      exporters: [otlp, logging]
  telemetry:
    metrics:
      address: 0.0.0.0:8888
      level: basic
    logs:
      level: debug
EOF
)
```

My run command:
```
docker run --name otel -t \
  -e "AOT_CONFIG_CONTENT=$AOT_CONFIG_CONTENT" \
  -e "SERVICE_FILTERS=$SERVICE_FILTERS" \
  -d <my-custom-adot-with-routing-processor:v0.21.1>
  ```

Error:
```
2022/10/16 15:24:04 application run finished with error: failed to get config: cannot resolve the configuration: cannot retrieve the configuration: yaml: line 22: could not find expected ':'
```

It looks like final YAML is not composed correctly. How to tweak my my env variables, so final yaml will have correct syntax?
