### ISSUE TITLE
UNKNOWN: NoCredentialProviders if AWS_PROFILE is specified

### ISSUE THREAD

**Issue by noliva** [aws-observability/aws-otel-collector#156]
Hello,

I tried to set up locally the collector with the following configuration:
```yaml
version: "3"
services:
  aws-ot-collector:
    image: amazon/aws-otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml", "--log-level=DEBUG"]
    environment:
      - AWS_PROFILE=p3
      - AWS_REGION=eu-west-1
    volumes:
      - ./config-test.yaml:/etc/otel-agent-config.yaml
      - ~/.aws:/root/.aws
    ports:
      - "55680:55680" # OTLP receiver
```

But when submitting traces I get `{"stack":"Error: 2 UNKNOWN: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\n    at Object.exports.createStatusError`

But if instead of using `AWS_PROFILE` I add `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` then it works, so my docker-compose.yaml file looks like:

```yaml
version: "3"
services:
  aws-ot-collector:
    image: amazon/aws-otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml", "--log-level=DEBUG"]
    environment:
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
    volumes:
      - ./config-test.yaml:/etc/otel-agent-config.yaml
      - ~/.aws:/root/.aws
    ports:
      - "55680:55680" # OTLP receiver
```

My credentials file in `~/.aws/credentials` looks like
```
[p3]
aws_access_key_id=key
aws_secret_access_key=secret
```

And my `tracer.js` looks like:

```javascript
const { NodeTracerProvider } = require('@opentelemetry/node');
const { ConsoleSpanExporter, SimpleSpanProcessor } = require('@opentelemetry/tracing');
// const { CollectorTraceExporter } =  require('@opentelemetry/exporter-collector');
const { CollectorTraceExporter } = require('@opentelemetry/exporter-collector-grpc');
const { propagation } = require("@opentelemetry/api");

const { AwsXRayIdGenerator } = require('@aws/otel-aws-xray-id-generator');
const { AWSXRayPropagator } = require('@aws/otel-aws-xray-propagator');

propagation.setGlobalPropagator(new AWSXRayPropagator());

const provider = new NodeTracerProvider({
    idGenerator: new AwsXRayIdGenerator()
});

const otlpExporter = new CollectorTraceExporter({
    serviceName: 'service-hello',
    url: "localhost:55680"
});
const otlpProcessor = new SimpleSpanProcessor(otlpExporter);
provider.addSpanProcessor(otlpProcessor);

provider.register();
```

So I'm not really sure why this is not working
