### ISSUE TITLE
Error reading file "yaml: line 173: could not find expected ':'"

### ISSUE THREAD

**Issue by gwiesing** [aws-observability/aws-otel-collector#1673]
**Describe the bug**
We have deployed the ADOT collector on a fargate task and receive occassional errors when the prometheus receiver tries to read the targets file from the ecs observer.

**Steps to reproduce**
Deploy a ADOT container on ECS.

**What did you expect to see?**
Metrics collection is working. 

**What did you see instead?**
The errors we get:

Nov 26, 2022 @ 06:02:01.299file/file.go:337	Error reading file	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "discovery": "file", "path": "/etc/ecs_sd_targets.yaml", "error": "yaml: line 85: could not find expected ':'"}
Nov 25, 2022 @ 17:07:13.630 file/file.go:337	Error reading file	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "discovery": "file", "path": "/etc/ecs_sd_targets.yaml", "error": "yaml: line 173: could not find expected ':'"}
Nov 25, 2022 @ 12:49:08.052file/file.go:337	Error reading file	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "discovery": "file", "path": "/etc/ecs_sd_targets.yaml", "error": "yaml: line 340: could not find expected ':'"}
Nov 24, 2022 @ 18:31:08.847file/file.go:337	Error reading file	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "discovery": "file", "path": "/etc/ecs_sd_targets.yaml", "error": "yaml: line 85: could not find expected ':'"}
Nov 24, 2022 @ 04:16:21.415file/file.go:337	Error reading file	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "discovery": "file", "path": "/etc/ecs_sd_targets.yaml", "error": "yaml: line 424: could not find expected ':'"}

**Environment**
AWS Fargate. Our image is built from amazon/aws-otel-collector:v0.23.0

Receiver config
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "ecssd"
          scrape_interval: 60s
          file_sd_configs:
            - files:
                - '/etc/ecs_sd_targets.yaml' # MUST match the file name in ecs_observer.result_file
          relabel_configs: # Relabel here because label with __ prefix will be dropped by receiver.
            - source_labels: [ __meta_ecs_cluster_name ] # ClusterName
              action: replace
              target_label: ClusterName
            - source_labels: [ __meta_ecs_service_name ] # ServiceName
              action: replace
              target_label: ServiceName
            - source_labels: [ __meta_ecs_task_definition_family ] # TaskDefinitionFamily
              action: replace
              target_label: TaskDefinitionFamily
            - source_labels: [ __meta_ecs_task_launch_type ] # LaunchType
              action: replace
              target_label: LaunchType
            - source_labels: [ __meta_ecs_container_name ] # container_name
              action: replace
              target_label: container_name
            - action: labelmap # Convert docker labels on container to metric labels
              regex: ^__meta_ecs_container_labels_(.+)$ # Capture the key using regex, e.g. __meta_ecs_container_labels_Java_EMF_Metrics -> Java_EMF_Metrics
              replacement: '$$1'

exporters:
  prometheusremotewrite:
    namespace: apim
    endpoint: "${endpoint}"
    auth:
      authenticator: sigv4auth
  logging:
    loglevel: info

extensions:
  ecs_observer:                             # extension type is ecs_observer
    cluster_name: ${cluster}                # cluster name need to configured manually
    cluster_region: ${region}               # region can be configured directly or use AWS_REGION env var
    result_file: '/etc/ecs_sd_targets.yaml' # the directory for file must already exists
    refresh_interval: 60s                   # format is https://golang.org/pkg/time/#ParseDuration
    # custom name for 'job' so we can rename it back to 'job' using metricstransform processor
    job_label_name: prometheus_job
    services:
      - name_pattern: '${pattern}' # name pattern
        metrics_path: '/metrics'
        metrics_ports:
          - 24231     # port for fluent
          - 24232     # port for application (JMX, aggregator) exporter
          - 24233     # port for node exporter
          - 24234     # self
        job_name: prometheus-exporter-metrics
      - name_pattern: '${pattern}' # name pattern
        metrics_path: '/aggregated_metrics'
        metrics_ports:
          - 24231
          - 24232
        job_name: prometheus-exporter-aggregated-metrics
  sigv4auth:
    assume_role:
      arn: '${role}'
      sts_region: '${region}'

service:
  telemetry:
    logs:
      level: info
    metrics:
      level: normal
      address: 0.0.0.0:24234
  extensions: [ ecs_observer, sigv4auth ] # extension is declared outside pipelines
  pipelines:
    metrics:
      receivers: [ prometheus ]
      exporters: [ logging, prometheusremotewrite ]
```
CPU and memory in ECS are configured to be lowest 256/1024. The configuration is stored in SSM.
With CPU settings 256 the task is running at a (almost) constant 7-8% load.

We are running ECS clusters in different accounts and the error occurs in all.

**Additional context**
N/A
