### ISSUE TITLE
ADOT Collector with Receiver 'awscontainerinsightreceiver' doesn't start on EKS windows node

### ISSUE THREAD

**Issue by HansBraun** [aws-observability/aws-otel-collector#1697]
**Describe the bug**
ADOT Collector with Receiver awscontainerinsightreceiver doesn't start on EKS windows node

**Steps to reproduce**
I followed instructions on https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/windows-other-demo.md. I added the config below and start collector like this:

` & '.\Program Files\Amazon\AWSOTelCollector\aws-otel-collector-ctl.ps1' -c c:\my_own_config.yaml -a start`

**What did you expect to see?**
Collector should start or at least respond with some descriptive error message

**What did you see instead?**
```
Start-Service : Failed to start service 'ADOT Collector (AWSOTelCollector)'.
At C:\aws-otel-collector-ctl.ps1:96 char:12
+     $svc | Start-Service
+            ~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
```

aws-otel-collector.log says:

> {"level":"info","timestamp":"2022-12-09T15:48:55.894Z","caller":"service/telemetry.go:111","message":"Setting up own telemetry..."}
> {"level":"info","timestamp":"2022-12-09T15:48:55.900Z","caller":"service/telemetry.go:141","message":"Serving Prometheus metrics","address":":8888","level":"Basic"}
> {"level":"debug","timestamp":"2022-12-09T15:48:55.900Z","caller":"components/components.go:28","message":"Beta component. May change in the future.","kind":"exporter","data_type":"metrics","name":"awsemf","stability":"Beta"}
> {"level":"debug","timestamp":"2022-12-09T15:48:55.900Z","caller":"awsutil@v0.66.0/conn.go:60","message":"Using proxy address: ","kind":"exporter","data_type":"metrics","name":"awsemf","proxyAddr":""}
> {"level":"debug","timestamp":"2022-12-09T15:48:55.936Z","caller":"awsutil@v0.66.0/conn.go:148","message":"Fetch region from ec2 metadata","kind":"exporter","data_type":"metrics","name":"awsemf","region":"eu-central-1"}
> {"level":"info","timestamp":"2022-12-09T15:48:55.937Z","caller":"awsutil@v0.66.0/conn.go:267","message":"STS Endpoint ","kind":"exporter","data_type":"metrics","name":"awsemf","endpoint":"https://sts.eu-central-1.amazonaws.com"}
> {"level":"debug","timestamp":"2022-12-09T15:48:56.072Z","caller":"components/components.go:28","message":"Stable component.","kind":"processor","name":"batch","pipeline":"metrics","stability":"Stable"}
> {"level":"debug","timestamp":"2022-12-09T15:48:56.072Z","caller":"components/components.go:28","message":"Beta component. May change in the future.","kind":"receiver","name":"awscontainerinsightreceiver","pipeline":"metrics","stability":"Beta"}
> {"level":"info","timestamp":"2022-12-09T15:48:56.073Z","caller":"service/service.go:89","message":"Starting aws-otel-collector...","Version":"v0.24.0","NumCPU":2}
> {"level":"info","timestamp":"2022-12-09T15:48:56.073Z","caller":"extensions/extensions.go:41","message":"Starting extensions..."}
> {"level":"info","timestamp":"2022-12-09T15:48:56.073Z","caller":"pipelines/pipelines.go:74","message":"Starting exporters..."}
> {"level":"info","timestamp":"2022-12-09T15:48:56.073Z","caller":"pipelines/pipelines.go:78","message":"Exporter is starting...","kind":"exporter","data_type":"metrics","name":"awsemf"}
> {"level":"info","timestamp":"2022-12-09T15:48:56.073Z","caller":"pipelines/pipelines.go:82","message":"Exporter started.","kind":"exporter","data_type":"metrics","name":"awsemf"}
> {"level":"info","timestamp":"2022-12-09T15:48:56.073Z","caller":"pipelines/pipelines.go:86","message":"Starting processors..."}
> {"level":"info","timestamp":"2022-12-09T15:48:56.074Z","caller":"pipelines/pipelines.go:90","message":"Processor is starting...","kind":"processor","name":"batch","pipeline":"metrics"}
> {"level":"info","timestamp":"2022-12-09T15:48:56.074Z","caller":"pipelines/pipelines.go:94","message":"Processor started.","kind":"processor","name":"batch","pipeline":"metrics"}
> {"level":"info","timestamp":"2022-12-09T15:48:56.075Z","caller":"pipelines/pipelines.go:98","message":"Starting receivers..."}
> {"level":"info","timestamp":"2022-12-09T15:48:56.075Z","caller":"pipelines/pipelines.go:102","message":"Receiver is starting...","kind":"receiver","name":"awscontainerinsightreceiver","pipeline":"metrics"}
> {"level":"info","timestamp":"2022-12-09T15:48:56.076Z","caller":"service/service.go:115","message":"Starting shutdown..."}
> {"level":"info","timestamp":"2022-12-09T15:48:56.076Z","caller":"pipelines/pipelines.go:118","message":"Stopping receivers..."}
> {"level":"info","timestamp":"2022-12-09T15:48:56.076Z","caller":"pipelines/pipelines.go:125","message":"Stopping processors..."}
> {"level":"info","timestamp":"2022-12-09T15:48:56.076Z","caller":"pipelines/pipelines.go:132","message":"Stopping exporters..."}
> {"level":"info","timestamp":"2022-12-09T15:48:56.076Z","caller":"extensions/extensions.go:55","message":"Stopping extensions..."}
> {"level":"info","timestamp":"2022-12-09T15:48:56.077Z","caller":"service/service.go:129","message":"Shutdown complete."}

The windows event log shows the following entry:

> Message : The ADOT Collector service terminated with the following error:
>           An exception occurred in the service when handling the control request.

**Environment**
I am running on a windoes node in a EKS cluster. When I run the same config on a linux node it works as expected.(I followed the example here: https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/otel-container-insights-infra.yaml)

I already tried to increase timeout of services via registry value and I am running as administrator.

Collector config file:

```
extensions:
      health_check:
    receivers:
      awscontainerinsightreceiver:
    processors:
      batch/metrics:
        timeout: 60s
    exporters:
      awsemf:
        namespace: ContainerInsights
        log_retention: 90
        log_group_name: '/aws/containerinsights/{ClusterName}-/performance'
        log_stream_name: '{NodeName}'
        resource_to_telemetry_conversion:
          enabled: true
        dimension_rollup_option: NoDimensionRollup
        parse_json_encoded_attr_values: [Sources, kubernetes]
        metric_declarations:
          # node metrics
          - dimensions: [[NodeName, InstanceId, ClusterName]]
            metric_name_selectors:
              - node_cpu_utilization
              - node_memory_utilization
              - node_network_total_bytes
              - node_cpu_reserved_capacity
              - node_memory_reserved_capacity
              - node_number_of_running_pods
              - node_number_of_running_containers
    service:
      pipelines:
        metrics:
          receivers: [awscontainerinsightreceiver]
          processors: [batch/metrics]
          exporters: [awsemf]

      extensions: [health_check]
```
