### ISSUE TITLE
[exporter/awsemfexporter] namespace is always set to cloudwatch namespace

### ISSUE THREAD

**Issue by crigertg** [aws-observability/aws-otel-collector#1712]
**Describe the bug**
I'm exporting `k8s` metrics to cloudwatch and want the namespace of the containers/services/pods to be visible as a Dimension. But currently this is not working because the awsemf exporter does of a `namespace` configuration parameter for the cloudwatch metrics namespace which seems to overwrite the Namespace which is available from the awscontainerinsightreceiver (see here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awscontainerinsightreceiver ). 

**Steps to reproduce**

1. Setup EKS cluster
2. install adot (you might use this [terraform module](https://registry.terraform.io/modules/makandra/adot/eks/latest)
3. Deploy configuration looking like the following (you might want to use this [helm chart](https://github.com/aws-observability/aws-otel-helm-charts)):

**What did you expect to see?**
I expect that the namespace attribute from the metric is set for the `dimensions` .

**What did you see instead?**
The cloudwatch namespace is set in the `dimensions`.

**Environment**

```
receivers:
  awscontainerinsightreceiver:
    collection_interval:  
    container_orchestrator:  
    add_service_as_attribute:  
    prefer_full_pod_name:  
    add_full_pod_name_metric_label:  
processors:
  batch/metrics:
    timeout: 60s
  attributes:
    actions:
      - key: foo
        action: insert
        value: bar
      - key: namespace
        action: insert
        from_attribute: Namespace
exporters:
  awsemf:
    namespace: ContainerInsights
    log_group_name: '/aws/containerinsights/eks-dev/performance'
    log_stream_name: InputNodeName
    region: eu-central-1
    resource_to_telemetry_conversion:
      enabled: true
    dimension_rollup_option: NoDimensionRollup
    parse_json_encoded_attr_values:
      - Sources
      - kubernetes.namespace_name
    metric_declarations:
      - dimensions: [[Service, Namespace, ClusterName], [ClusterName]]
        metric_name_selectors:
          - service_number_of_running_pods
service:
  pipelines:
    metrics:
      receivers:
      - awscontainerinsightreceiver
      processors:
      - batch/metrics
      - attributes
      exporters:
      - awsemf
  extensions:
  - health_check
```

**Additional context**

Cloudwatch logs output:

```
{
    "ClusterName": "eks-dev",
    "Namespace": "loki",
    "NodeName": "ip-10-1-79-141.eu-central-1.compute.internal",
    "Service": "loki",
    "Sources": [
        "apiserver"
    ],
    "Timestamp": "1670489791032",
    "Type": "ClusterService",
    "Version": "0",
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "ContainerInsights",
                "Dimensions": [
                    [
                        "ClusterName",
                        "Namespace",
                        "Service"
                    ],
                    [
                        "ClusterName"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "service_number_of_running_pods",
                        "Unit": "Count"
                    }
                ]
            }
        ],
        "Timestamp": 1670489791032
    },
    "foo": "bar",
    "kubernetes": "{\"namespace_name\":\"loki\",\"service_name\":\"loki\"}",
    "service_number_of_running_pods": 1
}
```

I've opened a ticket in [[opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib)](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17024) too.
