### ISSUE TITLE
Prometheus receiver configuration in aws-otel-collector to scrap metrics from EC2

### ISSUE THREAD

**Issue by banandh** [aws-observability/aws-otel-collector#1754]
Setup - Applications are running on ec2 instances, its not kubernates or docker based app.  Standard springboot executable jar is deployed on EC2

Have setup aws-otel-collector and aws open telemetry javaagent  in a single EC2, agent is able to push the data to collector.

Now, I'm trying to export the metrics to AWS managed Prometheus(AMP).

With aws-otel-collector , I have seen an option to define the prometheus receiver in collector config and using prometheusRemoteWriter we can export the same to AMP.

Issue:
Having issues with Prometheus receiver configuration

Collector Configuration

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    global:
      scrape_interval: 1m
      scrape_timeout: 10s
    scrape_configs:
      job_name: MY_JOB
      sample_limit: 10000
      ec2_sd_configs:
        region: us-east-1
        port: 9404
        filters:
          name: instance-id
          values:
            i-XXXXXX
              
processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: "XXXX/api/v1/remote_write"   

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
```

**Error while running the collector**

```
2023/01/11 05:52:16 ADOT Collector version: v0.23.1
Error: failed to get config: cannot unmarshal the configuration: error reading receivers configuration for "prometheus": prometheus receiver failed to parse config: 1 error(s) decoding:

*** '' has invalid keys: global, scrape_configs**
```

My understanding is ec2_sd_config - can get the metrics from the specified instance and exporter (RemoteWriter can send this info to AMP) Please correct ,if something is wrong in the above configuration.

Also I need some help on prometheusremotewrite authentication part , how to setup 

``` 
config: |
    extensions:
      sigv4auth:
        region: "<YOUR_AWS_REGION>"
        service: "aps"       

exporters:
      prometheusremotewrite:
        endpoint: <YOUR_REMOTE_WRITE_ENDPOINT>
        auth:
          authenticator: sigv4auth
```

What value to come in the `service:aps` , is this config enough for connecting the ADOT collector to AMP?

**Comment by Aneurysm9** [comment]
The `prometheus` receiver configuration should have a `config` entry under which your existing Prometheus configuration can be placed, like so:

```yaml
  prometheus:
    config:
      global:
        scrape_interval: 1m
        scrape_timeout: 10s
      scrape_configs:
        job_name: MY_JOB
        sample_limit: 10000
        ec2_sd_configs:
          region: us-east-1
          port: 9404
          filters:
            name: instance-id
            values:
              i-XXXXXX
```

Was there an example or documentation you were following that had the incorrect structure?  I'd like to get that fixed if there is.

Note that you'll also need to add the `prometheus` receiver to your `metrics` pipeline.  This can be done alongside the `otlp` receiver:

```yaml
service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
```

Your `sigv4auth` extension configuration looks correct, modulo placeholders.  The `aps` service value is the IAM identifier for AMP, though you should be able to omit it as it should be detected from the `endpoint` configured in the `prometheusremotewrite` exporter that is using the extension.
