### ISSUE TITLE
Setting cloudwatch log group so that logs appear in Cloudwatch Traces

### ISSUE THREAD

**Issue by nikhil-pandey** [aws-observability/aws-otel-collector#1766]
**Describe the question**
We have multiple services in ECS, aws-otel-collector is one of them and all the services report traces to this one instance of aws-otel-collector. Right now only traces data go through the aws-otel-collector.

Here's the config we're using
```yaml
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

exporters:
  awsxray:
    index_all_attributes: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [awsxray]

  extensions: [health_check]
```

Each service has two environment variables set: `OTEL_RESOURCE_ATTRIBUTES` and `OTEL_SERVICE_NAME`. `OTEL_RESOURCE_ATTRIBUTES` contains the following:
- `service.namespace`
- `service.version`
- `container.image.tag`
- `aws.log.group.names`
- `aws.log.group.arns`

Here's what the xray document looks like in cloudwatch
```
{
    "Id": "1-63c8b8cc-5e6c41bad8225f90bc5bc3c0",
    "Duration": 0.008,
    "LimitExceeded": false,
    "Segments": [
        {
            "Id": "5c2e8e8f2b2197cd",
            "Document": {
                "id": "5c2e8e8f2b2197cd",
                "name": "AppName",
                "start_time": 1674098892.2819598,
                "trace_id": "1-63c8b8cc-5e6c41bad8225f90bc5bc3c0",
                "end_time": 1674098892.2904406,
                "fault": false,
                "error": false,
                "throttle": false,
                "http": {
                    "request": {
                        "url": "http://<Url>",
                        "method": "POST",
                        "user_agent": "<UserAgent>"
                    },
                    "response": {
                        "status": 200,
                        "content_length": 0
                    }
                },
                "aws": {
                    "ecs": {
                        "container_id": "c4ae1a0b08671a6312fa7/e8538e8f62bc4ae1a0b08671a6312fa7-265927825"
                    },
                    "xray": {
                        "auto_instrumentation": false
                    }
                },
                "annotations": {
                    "otel_resource_cloud_provider": "aws",
                    "otel_resource_container_runtime": "docker",
                    "http_route": "/some/fun/route",
                    "http_flavor": "1.1",
                    "otel_resource_cloud_platform": "aws_ecs",
                    "otel_resource_container_image_name": "<accountId>.dkr.ecr.<region>.amazonaws.com/<repo>",
                    "otel_resource_container_image_tag": "AmazingTag",
                    "otel_resource_container_id": "c4ae1a0b08671a6312fa7/e8538e8f62bc4ae1a0b08671a6312fa7-265927825",
                    "otel_resource_aws_log_group_names": "MyAmazingLogGroup/Development",
                    "otel_resource_service_version": "5ba787d34761bcf4486b79eec9e4666486f79795",
                    "otel_resource_aws_log_group_arns": "arn:aws:logs:<region>:<accountId>:log-group:MyAmazingLogGroup/Development:*",
                    "otel_resource_service_namespace": "Development",
                    "otel_resource_service_name": "AppName"
                },
                "service": {
                    "version": "5ba787d34761bcf4486b79eec9e4666486f79795"
                },
                "origin": "AWS::ECS::Container",
                "subsegments": [
                    ...
                ]
            }
        },
       ...
    ]
}
```

**What did you expect to see?**

Logs don't show up on Traces page.

- Setting `aws.log.group.arns` metadata does nothing?
- Based on [this doc](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html), `aws.cloudwatch_logs.log_group` and `aws.cloudwatch_logs.arn` define the log group in Segment document. Will setting that fix this? Is there a way to set this or plans to get this from opentelemetry schema?

![Screenshot 2023-01-18 at 10 36 22 PM](https://user-images.githubusercontent.com/3397134/213349600-0a27998e-89a1-44e5-a759-abc3a9cd394f.png)
