### ISSUE TITLE
log_retention for the awsemf doesn't appear to be working

### ISSUE THREAD

**Issue by lorelei-rupp-imprivata** [aws-observability/aws-otel-collector#1768]
**Describe the bug**
This was fixed by https://github.com/aws-observability/aws-otel-collector/issues/991
But I am not seeing this actually work when trying to implement it

**Steps to reproduce**
Rolled out 0.25.0 of the collector
Updated my config map to have something like 
```
apiVersion: v1
data:
  collector.yaml: |
    exporters:
      awsemf:
        dimension_rollup_option: NoDimensionRollup
        log_group_name: /aws/containerinsights/{ClusterName}/performance
        log_retention: 7
        log_stream_name: '{NodeName}'
......
```
Rolled this out, then manually deleted the log group in cloud watch
It was recreated, however no log retention was set, still says Never Expire

**What did you expect to see?**
Log retention would be set on the new log group that was created

Can provide more things if necessary
Maybe I am not implementing this properly

@bryan-aguilar @humivo 

We are using the Daemonset to roll this out with the adot operator
I bumped up to image: 'amazon/aws-otel-collector:v0.25.0'

**Comment by bryan-aguilar** [comment]
I was not able to replicate this on my local system using this config.
```
exporters:
  awsxray:
    region: us-west-2
    local_mode: true
    no_verify_ssl: true
  awsemf:
    region: us-west-2
    dimension_rollup_option: NoDimensionRollup
    log_group_name: /aws/containerinsights/testtest/performance
    log_retention: 7
    log_stream_name: 'testNodeStreamName'
  logging:
    loglevel: debug
```
![image](https://user-images.githubusercontent.com/46550959/213519589-1cde731c-f21f-48f6-987b-7b5bc91be379.png)

I'm wondering if the fact that it's deployed through a deamonset has something to do with it. @lorelei-rupp-imprivata could you try reproducing this with a minimal config and daemonset? If you can reproduce again can you share the deamonset manifest? I also wonder if there if something is getting messed up with the `{ClusterName}` substitution. I'm not familiar with this code and will loop @humivo in. Could you also try a fixed `log group` and `log stream` name for testing @lorelei-rupp-imprivata?

**Comment by lorelei-rupp-imprivata** [comment]
Let me try a fixed log_stream_name and a fixed_log_group_name.

I don't thin our config is that advanced either. Im happy to provide our config map if you want it

**Comment by lorelei-rupp-imprivata** [comment]
I tested with fixed stuff and still did not work

```
    exporters:
        awsemf:
          namespace: ContainerInsights
          log_group_name: /aws/containerinsights/testtest/performance
          log_retention: 7
          log_stream_name: 'testNodeStreamName'
          resource_to_telemetry_conversion:
            enabled: true
          dimension_rollup_option: NoDimensionRollup
          parse_json_encoded_attr_values: [Sources, kubernetes]
          metric_declarations:
.....
```
