### ISSUE TITLE
Xray exporter ignoring producer and consumer spanKinds

### ISSUE THREAD

**Issue by dngferreira** [aws-observability/aws-otel-collector#1773]
**Describe the bug**
Xray exporter only creates services for span kind of type Server or client.

**Steps to reproduce**
I have a scenario where two application written in python communicate using rabbitmq, S1 and S2.
S1 sends a message to rabbitmq, S2 reads it, stores in Redis and returns a message to S1 through rabbitmq in another channel.
Enable opentelemetry instrumentation with Pika, Redis and Flask instrumentations all default sending to ADOT collector with a x-ray exporter

**What did you expect to see?**
On the service map I was expecting to see 4 services:
S1
Rabbitmq
S2
Redis

**What did you see instead?**
On the service map I see 2 services:
S1 with rabbitmq and S2 spans as subsegments
Redis

**Environment**
```
extensions:
  health_check:
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50    
  resourcedetection/eks:
    detectors: [env, eks, ecs, ec2]
    timeout: 2s
    override: false
exporters:
  logging:
    loglevel: debug
  awsxray:
    index_all_attributes: true
    region: "us-east-1"
service:  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection/eks, batch/traces]
      exporters: [logging, awsxray]
```

**Additional context**
