### ISSUE TITLE
Disabling the sending_queue prevents metrics from exported

### ISSUE THREAD

**Issue by JustinPaulJohn** [aws-observability/aws-otel-collector#1825]
**Describe the question**
Disabling the sending_queue within the otlp-exporter prevents all metric data (both receiver and exporter) from being sent.
Metrics are still being generated on the localhost:8888/metrics endpoint, however, our Prometheus scrape config (which is setup to scrape that endpoint) is unable to receive any metric data. Prometheus logs show no indication of any errors while scrapping, so the job is working as intended. Re-enabling the sending_queue allows metrics to be sent like normal, however, our current environment requires the sending_queue to be disabled. Is there any way to keep the sending_queue disabled while allowing metrics to be exported? Any relevant documentation regarding how the sending_queue works would be appreciated too.

**Steps to reproduce if your question is related to an action**

- Set `sending_queue` in `exporter` to `enabled:false`
- Setup Prometheus Scrape Job Config to scrape application at localhost:8888/metrics

**What did you expect to see?**
- Metrics from collector should appear within Prometheus while  `sending_queue` is disabled

**Environment**
Collector Version - v0.17.0
```
extensions:
  health_check:

recievers:
  otlp:
    protocols:
      grpc:
        endpoint: ...
      http:
        endpoint: ...

processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200

exporters:
  otlp:
    endpoint: ...
    retry_on_failure:
      enabled: true
      max_elapsed_time: 120s
    sending_queue:
      enabled: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

  extensions: [health_check]
```

**Additional context**
