### ISSUE TITLE
SSM and SecretsManager Config Variable support

### ISSUE THREAD

**Issue by driverpt** [aws-observability/aws-otel-collector#1894]
**Is your feature request related to a problem? Please describe.**
We would like to run OTEL Collector as Lambda Layer but we need the External Provider Key to be injected from AWS SecretsManager.
The purpose is to prevent attaching Lambdas to VPC to avoid IP Exhaustion.

**Describe the solution you'd like**
Have a custom AWS Config Provider in OTEL Config, e.g.:

```yaml
receivers:
    otlp:
      protocols:
        grpc:
        http:
    exporters:
      otlp/external_provider:
        endpoint: "<external_provider_url>"
        headers:
           api-key: ${secretsmanager:${env:SECRET_ARN}}
           compression: gzip
    processors:
    extensions:
    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp/external_provider]
```

**Describe alternatives you've considered**
N/A

**Additional context**
External Providers as in DataDog, NewRelic, Splunk, etc.....
