### ISSUE TITLE
Adding 2 prometheusremotewrite exporters in the same OTEL collector configuration

### ISSUE THREAD

**Issue by realmohan001** [aws-observability/aws-otel-collector#1907]
How to add two prometheusremotewrite exporters in the same OTEL collector configuration?

We are trying to send metrics to us-east-1 and US-west-2

I tried adding exporters with different names, but got this below error,

directory
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'exporters': unknown type: "prometheusremotewrite-east" for id: "prometheusremotewrite-east" (valid values: [logzio prometheus sapm datadog file dynatrace signalfx logging otlp awsxray awsemf prometheusremotewrite otlphttp])
2023/03/13 19:46:46 application run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'exporters': unknown type: "prometheusremotewrite-east" for id: "prometheusremotewrite-east" (valid values: [logzio prometheus sapm datadog file dynatrace signalfx logging otlp awsxray awsemf prometheusremotewrite otlphttp])

Any help would be appreciated!

**Comment by mhausenblas** [comment]
As per upstream docs [collector configuration](https://opentelemetry.io/docs/collector/configuration/) where it says:

> Note that receivers, processors, exporters and/or pipelines are defined via component identifiers in type[/name] format (e.g. otlp or otlp/2). Components of a given type can be defined more than once as long as the identifiers are unique

So, in your case something along the line of the following should work (note that you need to replace `https://aws-managed-prometheus-endpoint/` with your respective Amazon Managed Service for Prometheus  endpoints):

```
receivers:
  prometheus:
    config:
      ...

processors:
  batch:

extensions:
  sigv4auth/east:
    service: "aps"
    region: "us-east-1"
  sigv4auth/west:
    service: "aps"
    region: "us-west-2"

exporters:
  prometheusremotewrite/east:
    endpoint: "https://aws-managed-prometheus-endpoint/v1/api/remote_write"
    auth:
      authenticator: sigv4auth/east
  prometheusremotewrite/west:
    endpoint: "https://aws-managed-prometheus-endpoint/v1/api/remote_write"
    auth:
      authenticator: sigv4auth/west

service:
  pipelines:
    metrics/east:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite/east]
    metrics/west:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite/west]
```
