### ISSUE TITLE
ConnectionError and ReadTimeout when using ALB

### ISSUE THREAD

**Issue by danw-mpl** [aws-observability/aws-otel-collector#1919]
**Describe the bug**
When running the ADOT collector as a Fargate service with an ALB in front, we get random errors such as `ConnectionError` and `ReadTimeout`.  This does not happen if we direct our exporters to a Fargate container IP address.

`('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

`HTTPSConnectionPool(host='opentelemetry-collector.eu-west-1..., port=443): Read timed out. (read timeout=10)`

We've since swapped to gRPC as a workaround but would like to use http/protobuf for less dependencies.

I wonder if this is an idle timeout configuration issue on the collector?  In most applications, we set the application idle timeout higher than the ALB idle timeout.  I can only find a way to alter this for gRPC.

**Steps to reproduce**

Collector config:
```yaml
receivers:
  otlp:
    protocols:
      http:
      grpc:
        keepalive:
          server_parameters:
            max_connection_idle: 900s
            timeout: 900s

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50

extensions:
  health_check:

exporters:
  awsxray:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [
        batch/traces
      ]
      exporters: [awsxray]
```

**What did you expect to see?**
No timeouts.

**What did you see instead?**
Timeouts.

**Environment**
AWS, eu-west-1.  Apps and collector deployed in same region. Collector deployed using AWS CDK via `ApplicationLoadBalancedFargateService`. Python apps.
