### ISSUE TITLE
Add basicauth extension to collectors

### ISSUE THREAD

**Issue by cedricziel** [aws-observability/aws-otel-collector#1930]
**Is your feature request related to a problem? Please describe.**
As a user, I want to use credentials in a transparent way, without having to transform them first. As such, `basic` auth credentials currently have to be base64 encoded and passed as raw header array.

```yaml
receivers:
  otlp:
exporters:
  otlphttp:
    endpoint: ${OTLPHTTP_ENDPOINT}
    headers:
      Authorization: "Basic base64encodedcreds="
processors:
  batch:
extensions:
  health_check:
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
```

**Describe the solution you'd like**
The otelcol-contrib offers a `basicauth` extension so configuration and secret values become more readable and less opaque.

The following example uses the extension and allows users to work with explicit values instead of opaque strings:

```yaml
receivers:
  otlp:
exporters:
  otlphttp:
    auth:
      authenticator: basicauth
    endpoint: ${OTLPHTTP_ENDPOINT}
processors:
  batch:
extensions:
  health_check:
  basicauth:
    client_auth:
      username: ${USERNAME}
      password: ${PASSWORD}
service:
  extensions: [health_check, basicauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
```

I thought this was a straight forward change so I added the implementation in #1923 which is ready to bring in. The extension itself is very lean and doesnt add a lot of overhead in the binary or the startup.

**Comment by jonbretman** [comment]
Would also love to see this land 🙌  For example this is how Grafana's docs suggest to set up the collector - https://grafana.com/docs/grafana-cloud/data-configuration/otlp/send-data-otlp/#push-using-the-opentelemetry-collector

**Comment by eriweb** [comment]
Plus one from here as well, also we'd like to see oauth2client extension to allow more sophisticated 3rd parties

**Comment by cedricziel** [comment]
Bump?

**Comment by johnjunjiezhao** [comment]
Updates on it? I really want this extension!

**Comment by mhausenblas** [comment]
Thanks for reaching out @johnjunjiezhao and could you share your use case please?

**Comment by johnjunjiezhao** [comment]
Hi @mhausenblas , I want the adot sidecar on my ecs cluster also sends traces to grafana cloud. According their guide, I need this extension. https://grafana.com/docs/opentelemetry/collector/send-otlp-to-grafana-cloud-databases/ I think it will be convenient if adot can have it. Thanks!

**Comment by wjoel** [comment]
@johnjunjiezhao if you can use Grafana's [OTLP gateway](https://grafana.com/docs/grafana-cloud/monitor-infrastructure/otlp/send-data-otlp/) (currently only available in some regions) it's possible to send data to Grafana Cloud with a config similar to this:
```yaml
exporters:
  otlphttp:
    endpoint: "https://otlp-gateway-prod-eu-west-2.grafana.net/otlp"
    headers: {"Authorization": "Basic the-base64-encoded-value"}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch/logs]
      exporters: [otlphttp]
```
where `the-base64-encoded-value` is the output from `echo -n $GRAFANA_INSTANCE_ID:$TOKEN | base64 -w 0`.

I suspect it's possible to set the basic auth header manually like this also for https://grafana.com/docs/opentelemetry/collector/send-otlp-to-grafana-cloud-databases/, but I haven't tried it, as I'm able to use Grafana's OTLP gateway.

Still, +1 for requesting the extension, it would make using basic auth easier and clearer.
