### ISSUE TITLE
Metrics data dropped due to `out of order sample` error when running multiple replicas of adot-otel-collector and using batch/metrics processor

### ISSUE THREAD

**Issue by nbrational** [aws-observability/aws-otel-collector#1984]
**Describe the bug**
As per [docs](https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/installation#deployment-mode) `you can relatively easily scale up the Collector to monitor more targets`. This means that multiple PODs for collector could be run at the same time. But when using `batch/metrics` processor with multiple collectors, below error occurs

`
2023-04-17T13:53:44.619Z	error	exporterhelper/queued_retry.go:394	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): user=419264005465_ws-56c6fd97-30fe-4250-bd32-2ff3268e6b23: err: out of order sample. timestamp=2023-04-17T13:52:50.001Z, series={__name__=\"scrape_samples_scraped\", instance=\"172.31.78.22:8888\", job=\"adot-collector\", pod_ip=\"172.31.78.22\", pod_name=\"observa", "dropped_items": 88}
`

**Steps to reproduce**
Example config

```
apiVersion: opentelemetry.io/v1alpha1 
kind: OpenTelemetryCollector
metadata:
  labels:
    app.kubernetes.io/managed-by : opentelemetry-operator
  name: observability
  namespace: aws-otel-eks
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          global:
            scrape_interval: 20s
            scrape_timeout: 10s
          scrape_configs:
            - job_name: adot-collector
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    own_namespace: true
                    names:
                    - aws-otel-eks
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_container_port_name]
                  regex: metrics
                  action: keep
                - source_labels: [ __meta_kubernetes_pod_name ]
                  action: replace
                  target_label: pod_name
                - source_labels: [ __meta_kubernetes_pod_ip ]
                  action: replace
                  target_label: pod_ip
                - source_labels: [ __meta_kubernetes_pod_node_name ]
                  action: replace
                  target_label: pod_on_node

    processors:
      batch/metrics:
        timeout: 60s         

    exporters:
      prometheusremotewrite:
        endpoint: "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/api/v1/remote_write "
        auth:
          authenticator: sigv4auth
    
    extensions:
      sigv4auth:
        region: "us-east-1"
        service: "aps"

    service:
      extensions: [sigv4auth]
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch/metrics]
          exporters: [prometheusremotewrite]

  mode: deployment
  replicas: 2
  serviceAccount: aws-otel-collector
  targetAllocator:
    prometheusCR: {}
```

**What did you expect to see?**
Metrics successfully ingested in AMP and no `out of order sample` error

OR

A documentation to call out the limitation when using `batch/metrics` processor with multiple collectors

**What did you see instead?**
`out of order sample` error and data is dropped

`
2023-04-17T13:52:44.565Z	info	prometheusreceiver@v0.66.0/metrics_receiver.go:288	Starting scrape manager	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics"}
2023-04-17T13:53:44.619Z	error	exporterhelper/queued_retry.go:394	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): user=419264005465_ws-56c6fd97-30fe-4250-bd32-2ff3268e6b23: err: out of order sample. timestamp=2023-04-17T13:52:50.001Z, series={__name__=\"scrape_samples_scraped\", instance=\"172.31.78.22:8888\", job=\"adot-collector\", pod_ip=\"172.31.78.22\", pod_name=\"observa", "dropped_items": 88}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send 
	go.opentelemetry.io/collector@v0.66.0/exporter/exporterhelper/queued_retry.go:394 
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send 
	go.opentelemetry.io/collector@v0.66.0/exporter/exporterhelper/metrics.go:135 
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1 
	go.opentelemetry.io/collector@v0.66.0/exporter/exporterhelper/queued_retry.go:205 
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1 
	go.opentelemetry.io/collector@v0.66.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61 
`

**Environment**
*ADOT operator version*
adot-operator:v0.66.0

*otel collector version*
aws-otel-collector:v0.24.1

**Additional context**
N/A

**Comment by rapphil** [comment]
Hi,

This is not a limitation/problem of the `batch/metrics` processor. It is happening due to the fact you have 2 collector instances running at the same time ingesting the same data into Amazon Managed Prometheus. You get out of order errors because you are trying to ingest the same multiple times. Using the  `batch/metrics` processor will make this error happen more frequently because a batch will likely contain observations "from the past" for a certain metric that was successfully ingested by another collector.

To solve this while still having redundancy of collectors, I recommend that you use this feature of Amazon Managed Prometheus: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-ingest-dedupe.html#Send-high-availability-data-ADOT

I was able to reproduce your problem with the configuration that you shared and I was also able to test a solution based on the feature above.

Please consider adding the labels `cluster` and `__replica__` to the metrics ingested by both collectors as suggested in the documentation linked above. This can be achieved with the following configuration using the [metricstransform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor#metrics-transform-processor):

```
apiVersion: opentelemetry.io/v1alpha1 
kind: OpenTelemetryCollector
metadata:
  labels:
    app.kubernetes.io/managed-by : opentelemetry-operator
  name: observability
  namespace: aws-otel-eks
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          global:
            scrape_interval: 20s
            scrape_timeout: 10s
          scrape_configs:
            - job_name: adot-collector
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    own_namespace: true
                    names:
                    - aws-otel-eks
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_container_port_name]
                  regex: metrics
                  action: keep
                - source_labels: [ __meta_kubernetes_pod_name ]
                  action: replace
                  target_label: pod_name
                - source_labels: [ __meta_kubernetes_pod_ip ]
                  action: replace
                  target_label: pod_ip
                - source_labels: [ __meta_kubernetes_pod_node_name ]
                  action: replace
                  target_label: pod_on_node

    processors:
      metricstransform:
        transforms:
          - include: ".*"
            match_type: regexp
            action: update
            operations:
              - action: add_label
                new_label: cluster
                new_value: arbitrary-cluster-name
              - action: add_label
                new_label: __replica__
                new_value: ${env:POD_NAME}
      batch/metrics:
        timeout: 60s

    exporters:
      prometheusremotewrite:
        endpoint: "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/api/v1/remote_write "
        auth:
          authenticator: sigv4auth

    extensions:
      sigv4auth:
        region: "us-east-1"
        service: "aps"

    service:
      extensions: [sigv4auth]
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [metricstransform, batch/metrics]
          exporters: [prometheusremotewrite]

  mode: deployment
  replicas: 2
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  serviceAccount: aws-otel-collector
  targetAllocator:
    prometheusCR: {}
```
