### ISSUE TITLE
Health check not working

### ISSUE THREAD

**Issue by meijeran** [aws-observability/aws-otel-collector#2014]
**Describe the bug**
The health check for the AWS-OTel collector in Docker appears to not be working properly. The container becomes unhealthy after 15 seconds of running, despite the fact that the health check endpoint returns a healthy status when queried with a curl command.

**Steps to reproduce**
Build a custom Docker image using the following Dockerfile and the provided config.yml file:

Dockerfile
```Dockerfile
FROM public.ecr.aws/aws-observability/aws-otel-collector:v0.28.0

COPY config.yml /etc/ecs/config.yml
# start collector
CMD ["--config", "/etc/ecs/config.yml"]
```

Collector config:

```yaml
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  logging:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging]

```
Start a Docker container using the custom image, with the following command: `docker run -p 4317:4317 -p 13133:13133 --health-cmd='/healthcheck' --health-interval=5s baseinfra-otel:latest`
Wait for 15 seconds and check the container status using the docker ps command.

**What did you expect to see?**
I expected the container to remain healthy 

**What did you see instead?**
The container becomes unhealthy after 15 seconds, despite the fact that the health check endpoint returns a healthy status when queried with a curl command.

**Environment**
Docker version: 20.10.23, build 7155243
AWS-OTel collector version: v0.28.0
OS: macOS 13.3.1 (22E261)

**Additional context**
I have confirmed that the health check endpoint returns a healthy status when queried with `curl -f http://localhost:13133/`. The response from the curl command is: `{"status":"Server available","upSince":"2023-04-26T18:27:04.894164379Z","uptime":"4m51.530825174s"}%`. 
The provided Dockerfile includes the necessary steps to build a custom Docker image with the config.yml file copied into the container and the AWS-OTel collector started with the appropriate config file. I have also checked the Docker logs but did not find any relevant error messages.
