### ISSUE TITLE
ADOT Prometheus fails on file-not-found for file_sd_configs

### ISSUE THREAD

**Issue by JohnPreston** [aws-observability/aws-otel-collector#2039]
**Describe the bug**
With prometheus "native", the following configuration, in the absence of any files, would not fail. It would instead report the files are not present, and later on honor the `refresh_interval` and try again.

```yaml
scrape_configs:
  - job_name: "cdk_proxy_internal"
    scrape_interval: 1m
    file_sd_configs:
      - refresh_interval: 30s
        files:
          - /rendered_hosts/*.json
```

**Steps to reproduce**

```yaml
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 1m
        scrape_timeout: 10s

      scrape_configs:
        - job_name: "cdk_proxy_internal"
          scrape_interval: 1m
          file_sd_configs:
            - refresh_interval: 30s
              files:
                - /rendered_hosts/*.json

        - job_name: "cdk_proxy_public"
          scrape_interval: 1m
          file_sd_configs:
            - refresh_interval: 30s
              files:
                - /rendered_hosts/*.json

extensions:
  sigv4auth:
    service: "aps"
    region: "<aws_region>"

exporters:
  prometheusremotewrite:
    endpoint: "<remote_write_url>"
    auth:
      authenticator: sigv4auth


service:
  extensions:
    - sigv4auth
  pipelines:
    metrics:
      receivers:
        - prometheus
      exporters:
        - prometheusremotewrite

```

**What did you expect to see?**
I expect to see the prometheus receiver to honor the behaviour of prometheus missing files for `file_sd_configs`

**What did you see instead?**
ADOT Collector exit
```
2023/05/04 06:19:33 application run finished with error: invalid configuration: receivers::prometheus: file "/rendered_hosts/*.json" for file_sd in scrape job "cdk_proxy_internal" does not exist
```

**Environment**
ADOT Collector image used: public.ecr.aws/aws-observability/aws-otel-collector:latest

Thank you for your consideration,
