### ISSUE TITLE
xray exclude some path from metrics

### ISSUE THREAD

**Issue by ghdiska** [aws-observability/aws-otel-collector#2116]
**Describe the question**
i would like to exclude some path ( for example  /*/actuator/* ) from traces sent to xray

**What did you expect to see?**
I expect to not find in xray some path.

**Environment**
Describe any aspect of your environment.
If this is related to a deployment of the ADOT Collector please
provide your Collector config file. 

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector-xray
  namespace: monitoring
spec:
  mode: deployment
  resources:
    requests:
      cpu: "470m"
      memory: "688Mi"
    limits:
      cpu: "470m"
      memory: "688Mi"
  serviceAccount: adot-collector-irsa
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50

    exporters:
      awsxray:
        region: eu-south-1

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [awsxray]

```
