### ISSUE TITLE
How to add custom span attribute to get picked up by adot emf exporter?

### ISSUE THREAD

**Issue by Ryang20718** [aws-observability/aws-otel-collector#2142]
**Describe the question**
Hi, I couldn't find the docs to add a custom attribute when sending metrics to cloudwatch via the emf exporter. I'm looking to add something like `http.api_route` but it doesn't seem to be getting added to the metrics exporter. If I'm debugging my traces, I do see the additional attribute

**Steps to reproduce if your question is related to an action**
e.g in my custom gin middleware, I added some attributes which I expect to see in the CW metrics
```
func OtelGinMiddleware(serviceName string) gin.HandlerFunc {
	otelMiddleware := otelgin.Middleware(serviceName)

	return func(c *gin.Context) {
		ctx := c.Request.Context()
		span := trace.SpanFromContext(ctx)
		span.SetAttributes(attribute.String("http.api_route", c.FullPath()))
		span.SetAttributes(attribute.String("metadata.api_route", c.FullPath()))
		span.SetAttributes(attribute.String("api_route", c.FullPath()))
		span.SetAttributes(attribute.String("test", "testing"))
		otelMiddleware(c)
	}
}

```

**What did you expect to see?**
I expected to see this attribute within my cloudwatch metrics

**Environment**
Describe any aspect of your environment.
```
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
        endpoint: 0.0.0.0:4317

processors:
  attributes/traces:
      actions:
        - key: http.api_route
          from_context: metadata.api_route
          action: upsert
  batch:

exporters:
  logging:
    loglevel: debug
#  awsxray:
#    region: 'us-east-2'
  awsemf:
    region: 'us-east-2'

service:
  pipelines:
 #   traces:
 #     receivers: [otlp]
 #     exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf]

  extensions: [pprof]
  telemetry:
    logs:
      level: debug
```

**Additional context**
