### ISSUE TITLE
prometheusremotewrite exporter fails: remote write returned HTTP status 404 Not Found ... Workspace not found

### ISSUE THREAD

**Issue by syr** [aws-observability/aws-otel-collector#2155]
Using ADOT Collector v0.30.0, was working through documentation 
https://aws-otel.github.io/docs/getting-started/prometheus-remote-write-exporter/ecs
to eventually get prometheusremotewrite exporter to send metrics to AMP (running in another AWS account), using otel config based on  https://github.com/aws-observability/aws-otel-collector/blob/main/examples/ecs/aws-prometheus/ecs-fargate-adot-config.yaml
with prometheusremotewrite config adapted to:

```  
  prometheusremotewrite:
      endpoint: https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-<UUID>/api/v1/remote_write
      auth:
        authenticator: sigv4auth
```

Getting error in otel collector log
```  

2023-06-20T13:42:53.329Z	error	exporterhelper/queued_retry.go:391	Exporting failed. The error is not retryable. Dropping data.	
{
    "kind": "exporter",
    "data_type": "metrics",
    "name": "prometheusremotewrite",
    "error": "Permanent error: Permanent error: remote write returned HTTP status 404 Not Found; err = %!w(<nil>): {\"Message\":\"Workspace not found\"}",
    "dropped_items": 106
}
```  

Any idea what could be wrong or any hint how to analyse the issue?

Btw. awsemf exporter worked as expected, already exporting metrics which are visible in AWS Cloudwatch Metrics

**Additional context**

aws otel collector config
```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "my-app"
        static_configs:
        - targets: [ 0.0.0.0:8080 ]
  awsecscontainermetrics:
    collection_interval: 20s

processors:
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.utilized
          - ecs.task.memory.reserved
          - ecs.task.cpu.utilized
          - ecs.task.cpu.reserved
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes

exporters:
  logging:
    loglevel: debug
  awsemf:
      region: 'eu-central-1'
      resource_to_telemetry_conversion:
          enabled: true
  prometheusremotewrite:
      endpoint: https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-<UUID>/api/v1/remote_write
      auth:
        authenticator: sigv4auth

extensions:
  health_check:
  sigv4auth:
    region: 'eu-central-1'
    service: aps

service:
  extensions: [health_check, sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging,awsemf,prometheusremotewrite]
    metrics/ecs:
      receivers: [awsecscontainermetrics]
      processors: [filter]
      exporters: [logging,prometheusremotewrite]

  telemetry:
    logs:
      level: debug
```
