### ISSUE TITLE
AWS proxy does not work when using IRSA

### ISSUE THREAD

**Issue by guillomep** [aws-observability/aws-otel-collector#2159]
**Describe the bug**
I have deployed the ADOT collector and add the IAM role to use on the Service Account in order to get a working configuration for IRSA.
When trying to access the Xray AWS Proxy I get an error saying that the signature is not correct when calling `/GetSamplingRules`.

```json
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
```

**Steps to reproduce**
Deploy ADOT collector with the following files

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account id>:role/eks-cluster-test-adot-xray
  name: adot-collector
  namespace: test
---
apiVersion: v1
data:
  config.yaml: |-
    extensions:
      health_check:
      awsproxy:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
    exporters:
      awsxray:
        region: 'eu-west-1'
    service:
      extensions: [health_check,awsproxy]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [awsxray]
kind: ConfigMap
metadata:
  name: adot-collector
  namespace: test
---
apiVersion: v1
kind: Service
metadata:
  name: adot-collector
  namespace: test
spec:
  ports:
  - name: grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: awsproxy
    port: 2000
    protocol: TCP
    targetPort: 2000
  selector:
    app.kubernetes.io/instance: adot-collector
    app.kubernetes.io/name: adot-collector
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adot-collector
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: adot-collector
      app.kubernetes.io/name: adot-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: adot-collector
        app.kubernetes.io/name: adot-collector
    spec:
      containers:
      - args:
        - --config=file:/etc/adot/config.yaml
        env: null
        image: public.ecr.aws/aws-observability/aws-otel-collector:v0.30.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            port: 13133
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: collector
        ports:
        - containerPort: 4317
          name: grpc
          protocol: TCP
        - containerPort: 4318
          name: http
          protocol: TCP
        - containerPort: 2000
          name: awsproxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            port: 13133
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/adot/
          name: config
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccountName: adot-collector
      volumes:
      - configMap:
          name: adot-collector
        name: config
```

And the following role (`arn:aws:iam::<account id>:role/eks-cluster-test-adot-xray`):

Policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "xray:PutTraceSegments",
                "xray:PutTelemetryRecords",
                "xray:GetSamplingRules",
                "xray:GetSamplingTargets",
                "xray:GetSamplingStatisticSummaries"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

Trust relationship:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<account id>:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/<cluster id>"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.eu-west-1.amazonaws.com/id/<cluster id>sub": "system:serviceaccount:test:adot-collector"
                }
            }
        }
    ]
}
```

Then make a call to `/GetSamplingRules`.

**What did you expect to see?**
We should get a correct answer from `/GetSamplingRules` like the following

```json
{
  "NextToken": null,
  "SamplingRuleRecords": [
    ...
  ]
}
```

**What did you see instead?**

```json
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
```

**Environment**
The environment is AWS EKS 1.23 with the version of ADOT 0.30.0
