### ISSUE TITLE
No logs for prometheusremotewrite exporter in otel collector log

### ISSUE THREAD

**Issue by syr** [aws-observability/aws-otel-collector#2162]
We are trying to export metrics from AWS ECS container (running otel collector 0.30.0) to Amazon Managed Prometheus (AMP).
(otel collector config, see below.)

Receivers are both working, which we can see in logs from logging exporter.

Used exporters:  exporters: [logging,awsemf,prometheusremotewrite]

We see logs from logging and awsemf exporter (as well as logs from logging exporter and metrics in AWS cloudwatch from awsemf exporter.)

However, we see no logs for prometheusremotewrite exporter so cannot analyze what's the current problem with metrics export.

**Additional context**
otel collector 0.30.0 config

```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "my-app"
        static_configs:
        - targets: [ 0.0.0.0:8080 ]
  awsecscontainermetrics:
    collection_interval: 20s

processors:
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.utilized
          - ecs.task.memory.reserved
          - ecs.task.cpu.utilized
          - ecs.task.cpu.reserved
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes

exporters:
  logging:
    loglevel: debug
  awsemf:
      region: 'eu-central-1'
      resource_to_telemetry_conversion:
          enabled: true
  prometheusremotewrite:
      endpoint: https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-<UUID>/api/v1/remote_write
      auth:
        authenticator: sigv4auth

extensions:
  health_check:
  sigv4auth:
    region: 'eu-central-1'
    service: aps

service:
  extensions: [health_check, sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging,awsemf,prometheusremotewrite]
    metrics/ecs:
      receivers: [awsecscontainermetrics]
      processors: [filter]
      exporters: [logging,awsemf,prometheusremotewrite]

  telemetry:
    logs:
      level: debug
```
