### ISSUE TITLE
Does/Will awsxray exporter support retry_on_failure and sending_queue?

### ISSUE THREAD

**Issue by kinano** [aws-observability/aws-otel-collector#2204]
**Describe the question**
We are successfully using aws distro for otel collector to collect our app/server traces and export them to xray. I noticed that the [official otel exporter helper](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper#exporter-helper) mentions a few features that will help us handle intermittent export failures such as `retry_on_failure` and a `sending_queue`. When I searched aws-otel.github.io for these terms, I only found them mentioned for [Dynatrace Exporter](https://aws-otel.github.io/docs/partners/dynatrace). 

Is there a plan to support `retry_on_failure` and `sending_queue` on the [awsxray exporter](https://aws-otel.github.io/docs/getting-started/x-ray) in the future? My search for [retry_on_failure](https://github.com/aws-observability/aws-otel-collector/issues?q=retry_on_failure+) and [sending_queue](https://github.com/aws-observability/aws-otel-collector/issues?q=is%3Aissue+sending_queue+) only showed issues that include log messages emitted by the otel collector submitted by issue authors.

**Steps to reproduce if your question is related to an action**
When the awsxray exporter encounters any errors (in the following example I used bad AWS credentials), it will nudge the developer to enable `retry_on_failure` 
```
error	exporterhelper/queued_retry.go:367	Exporting failed. 
Try enabling retry_on_failure config option to retry on retryable errors	
{"kind": "exporter", "data_type": "traces", "name": "awsxray", "error": "Permanent error: UnrecognizedClientException: The security token included in the request is invalid.\n\tstatus code: 403}
```

**What did you expect to see?**
I was expecting awsxray exporter to support `retry_on_failure` and `sending_queue`. Adding these configs to the xray exporter has no effect  at the moment
```
exporters:
  logging:
    verbosity: detailed

  awsxray:
    index_all_attributes: true
    retry_on_failure:
      enabled: true
      max_elapsed_time: 10s
      initial_interval: 1s
      max_interval: 5s
      max_retries: 5
    sending_queue:
      enabled: true
```

**Additional context**
When I read the log message `Try enabling retry_on_failure config option to retry on retryable errors`, I figured perhaps the exporter knows that an AWS security error will never be `retryable` and I tried to trigger different intermittent errors such as disabling my network connection. I was not able to get the aws xray exporter to retry in any of these instances.
