### ISSUE TITLE
Support for the transform processor

### ISSUE THREAD

**Issue by bmbferreira** [aws-observability/aws-otel-collector#2300]
**Is your feature request related to a problem? Please describe.**

I'm using fluentbit to forward the logs to the opentelemetry collector and I want to parse the json from the logs and then transform some of the fields to attributes using the [transform procesor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor). However that processor doesn't seem to be supported by the AWS otel collector.

**Describe the solution you'd like**

I would like to have support for the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) to be able to do advanced transformations using the [Opentelemetry Transformation Language](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl).

**Describe alternatives you've considered**

Use the docker image from opentelemetry instead of using this one from AWS.

**Additional context**
N/A

**Comment by jangaraj** [comment]
I would like to have transform processor for my trace processing - I would like to rename `service.name` attribute if it is not in allowed set, e.g.:
```
transform:
  error_mode: ignore
  trace_statements:
    - context: resource
      statements:
        - set(attributes["service.name"], "not-whitelisted-service") where isMatch(["service-a","service-b"], attributes["service.name"])
```

**Comment by mhausenblas** [comment]
Thank you, @jangaraj

**Comment by puckpuck** [comment]
+1 to getting this processor added to ADOT. We are working with a customer for whom the lack of this processor is causing heartburn.

**Comment by bpholt** [comment]
FWIW, I think this is a dupe of #1869. Very much hope it is picked up soon!

**Comment by MaGaudin** [comment]
is there any update on this? it will be very very useful to have it.

**Comment by hodgiwabi** [comment]
+1 for this processor, in the context of [transforming histogram metrics for Dynatrace](https://docs.dynatrace.com/docs/extend-dynatrace/opentelemetry/getting-started/metrics/ingest/migration-guide-otlp-exporter#collector-histogram-transform)

**Comment by schmidt-galen-heb** [comment]
Bumping this issue again.

I'd like to use this processor to extract attributes from a log's `Scope`, which doesn't seem to be possible with the processors currently included in the ADOT collector, but seems like it would be trivial with this processor:

```yaml
transform/datadog/logs:
  error_mode: ignore
  log_statements:
    - context: log
      statements:
        - set(attributes["logger.name"], instrumentation_scope.name)
```

**Comment by will-sargent-eero** [comment]
bump, this matters because the opentelemetry-shim adds [links](https://github.com/open-telemetry/opentelemetry-java/blob/a686280aaf839f562ec33a4586ac6fd7018a9838/opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java#L209-L209) to every span and Honeycomb treats a link as an extra span in searches.

**Comment by RafaelGBAccenture** [comment]
This feature is essential for efficiently processing message content towards CloudWatch. Having the transform processor would enable us to parse and filter logs effectively, allowing for better data management and more accurate insights. This capability is critical for creating efficient log filters and improving overall system observability. Thank you for considering this request.

**Comment by pankdhnd** [comment]
+1 for this. Transform processor is useful not only for logs but also for traces. It provides functionality for traces that no other processor provides. Kindly consider this request to have transform processor support as a part of ADOT.

**Comment by pcesara** [comment]
+100 This would be a very welcome feature.

Another use case is to manage attributes in metrics data points.
For example, taking Resource attributes and adding them as attributes in either Spans or Metrics data points.

**Comment by will-sargent-eero** [comment]
No go stale please

**Comment by lasith-kg** [comment]
Transform Processor is an essential component of OTEL Collectors. Its applicability extends to Traces and Metrics. I believe its currently the only way to inject OTEL Resource Attributes into Prometheus Labels [Reference](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusexporter/README.md#setting-resource-attributes-as-metric-labels). 

I would love to see the Transform Processor included within the ADOT Collector package <3

**Comment by ns-mkusper** [comment]
This is the most useful processor out there for OTEL telemetry data. I hope support for it gets added to adot some day.

**Comment by schmidt-galen-heb** [comment]
This feature is still wanted

**Comment by agustints** [comment]
Hi, is there any updates on this?
I'm really looking forward to using the transform processor for the log_statements transformation. Thanks!

**Comment by TylerHelmuth** [comment]
The Transform Processor and OTTL are now considered Beta. Hopefully that makes it easier to add the processor to your manifest

**Comment by lasith-kg** [comment]
This is something that we are still interested in.

**Comment by gregbrowndev** [comment]
In addition to being able to add metric datapoint attributes (i.e.. for Prometheus labels), we could also use the `transform` processor to fix `awsecscontainermetrics` metric unit labels. 

`awsecscontainermetrics` generates OTLP format metrics, but with units that aren't standard OTLP or even Prometheus, e.g. "Bytes", "Count", "Percent", "vCPU", etc.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awsecscontainermetricsreceiver#available-metrics

If you use `prometheusexporter` or `prometheusremotewriteexporter` in the ADOT collector, or anywhere downstream, you get the wrong metric name in Prometheus, e.g. `ecs_task_memory_usage_Bytes`, `ecs_task_network_io_usage_rx_packets_Count`, etc.

With `transform` we can change the unit value, something like this (for OTLP compliance):

```
transform:
    metric_statements:
      - context: metric
        statements:
          - set(unit, "By") where name == "ecs.task.memory.usage"
          - set(unit, "By") where name == "ecs.task.memory.usage.limit"
          - set(unit, "1") where name == "ecs.task.cpu.usage.vcpu"
          - set(unit, "1") where name == "ecs.task.cpu.reserved"
          - set(unit, "By") where name == "ecs.task.network.io.usage.rx_bytes"
          - set(unit, "By") where name == "ecs.task.network.io.usage.tx_bytes"
          - set(unit, "1") where name == "ecs.task.network.io.usage.rx_packets"
          - set(unit, "1") where name == "ecs.task.network.io.usage.tx_packets"
          - set(unit, "1") where name == "ecs.task.network.io.usage.rx_errors"
          - set(unit, "1") where name == "ecs.task.network.io.usage.tx_errors"
          - set(unit, "1") where name == "ecs.task.network.io.usage.rx_dropped"
          - set(unit, "1") where name == "ecs.task.network.io.usage.tx_dropped"
          - set(unit, "By") where name == "ecs.task.storage.read_bytes"
          - set(unit, "By") where name == "ecs.task.storage.write_bytes"
```
