### ISSUE TITLE
ECS hosted ADOT collector is unable to write metrics to an AMP remote write endpoint

### ISSUE THREAD

**Issue by Rehne83** [aws-observability/aws-otel-collector#2351]
**Describe the bug**
ECS hosted ADOT collector is unable to write metrics to an AMP remote write endpoint. It throws the error below:

`2023-09-15T11:37:01.604Z error exporterhelper/queued_retry.go:364 Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: Permanent error: Post \"https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-09f824ad-d573-4664-818e-b57ffff6f242/api/v1/remote_write\": context deadline exceeded"}`

note, the issue persists when enabling retry on failure

**Steps to reproduce**
i am using the following otel config:

```
extensions:
  health_check:
  sigv4auth:
    region: "eu-central-1"
    service: "aps"
    
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
processors:
  batch:
exporters:
  logging:
    loglevel: "debug"
  prometheusremotewrite:
    # retry_on_failure:
    #   enabled: true
    #   initial_interval: 10s
    #   max_interval: 60s
    #   max_elapsed_time: 10m
    endpoint: "https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-09f824ad-d573-4664-818e-b57ffff6f242/api/v1/remote_write"
    auth:
      authenticator: sigv4auth

service:
  extensions: [health_check, sigv4auth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, logging]
```

**What did you expect to see?**
no error, instead exported metrics to prometheus

**What did you see instead?**
the error:
2023-09-15T11:37:01.604Z error exporterhelper/queued_retry.go:364 Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: Permanent error: Post \"https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-09f824ad-d573-4664-818e-b57ffff6f242/api/v1/remote_write\": context deadline exceeded"}

**Environment**
ECS hosted ADOT collector
AWS managed prometheus

**Additional context**
using curl/node to send otel metrics
