### ISSUE TITLE
ability to check Prometheus Receiver scrape target health

### ISSUE THREAD

**Issue by jessegoodier** [aws-observability/aws-otel-collector#2463]
**Describe the question**

Is it possible to check the health of the scrape jobs of the Prometheus Receiver when a target is down?
Even with debug logging, I see nothing, just that the job is added.

**Steps to reproduce if your question is related to an action**

I have:
```yaml
    exporters:
      logging:
        loglevel: debug
```

**What did you expect to see?**

Ideally, jobs with no targets scraping, like you see in the targets page of a prometheus UI.

**Environment**

my scrape config config:
```yaml
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s
          scrape_configs:
          - job_name: kubecost
            honor_labels: true
            # scrape_interval: 1m
            # scrape_timeout: 60s
            metrics_path: /metrics
            scheme: http
            dns_sd_configs:
            - names:
              - adot-primary-cost-analyzer.adot-kubecost-bad
              # ^ intentional mistake
              type: 'A'
              port: 9003
            relabel_configs:
            - source_labels: [__address__]
              target_label: alpha_eksctl_io_cluster_name
              replacement: qa-eks1
```

If this is documented somewhere, it is difficult to find.
