### ISSUE TITLE
Pod metrics not being collected using Bottlerocket

### ISSUE THREAD

**Issue by ElvenSpellmaker** [aws-observability/aws-otel-collector#2486]
**Describe the bug**
Getting this in the logs:
```
2023-11-15T17:48:30.160Z	warn	cadvisor/container_info_processor.go:82	No pod metric collected	{"kind": "receiver", "name": "awscontainerinsightreceiver", "data_type": "metrics", "metrics count": 40}
```

**Steps to reproduce**
Deploy the latest chart version 0.21.0 which ships the 0.35 of the app.

**What did you expect to see?**
Pod metrics being collected and shipped to CloudWatch

**What did you see instead?**
```
2023-11-15T17:48:30.160Z	warn	cadvisor/container_info_processor.go:82	No pod metric collected	{"kind": "receiver", "name": "awscontainerinsightreceiver", "data_type": "metrics", "metrics count": 40}
```

**Environment**
EKS using K8s 1.28
Bottlerocket Nodes
AMI Type: BOTTLEROCKET_x86_64
AMI Version: 1.16.0-d2d9cf87

Helm Values:
```
global:
  namespaceOverride: "aws-adot-otel"
awsRegion: "eu-west-2"
clusterName: "foo"
adotCollector:
  daemonSet:
    namespace: "aws-adot-otel"
    serviceAccount:
      name: "aws-adot-otel-sa"
      annotations:
        eks.amazonaws.com/role-arn: "arn:..."
    service:
      metrics:
        receivers: ["awscontainerinsightreceiver"]
        exporters: ["awsemf"]
```

**Additional context**
I thought this was solved in https://github.com/aws-observability/aws-otel-collector/issues/1071 but it seems it's still persisting for me.

It looks like `/run/dockershim.sock` should be mounted but isn't being mounted.
From: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-troubleshooting.html#ContainerInsights-troubleshooting-bottlerocket

![image](https://github.com/aws-observability/aws-otel-collector/assets/2286713/456c9698-5163-482c-8ab2-07b52e641e9f)
