### ISSUE TITLE
ADOT EKS addon (v0.88.0-eksbuild.1) misconfiguration for OTLP collector receiver

### ISSUE THREAD

**Issue by sastie-rai** [aws-observability/aws-otel-collector#2510]
**Issue**
The new EKS ADOT addon has a misconfiguration for the oltp collector receiver.
The config map generated for the adot-col-otlp-ingest deployment is as follows:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
```

this causes the collector to not be accessible from anywhere else but its own container:
a basic `curl -v http://adot-col-otlp-ingest:4318` results in a `connection refused error`

**Suggested fix**
Changing the config map in  the `opentelemetrycollector` named `adot-col-otlp-ingest` solves the issue:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
```

**Environment**
(running on EKS Platform version eks.3, with k8s 1.28)
```json
{
  "collector": {
    "containerLogs": {
      "pipelines": {
        "logs": {
          "cloudwatchLogs": {
            "enabled": false
          }
        }
      },
      "serviceAccount": {
        "annotations": {
          "eks.amazonaws.com/role-arn": "arn:aws:iam::xxxxxx:role/ADOTCollectorOltpContainerLogsRole"
        }
      }
    },
    "otlpIngest": {
      "pipelines": {
        "traces": {
          "xray": {
            "enabled": true
          }
        }
      },
      "serviceAccount": {
        "annotations": {
          "eks.amazonaws.com/role-arn": "arn:aws:iam::xxxxxx:role/ADOTCollectorOltpIngestRole"
        }
      }
    },
    "prometheusMetrics": {
      "exporters": {
        "prometheusremotewrite": {
          "endpoint": "https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-xxxxxx/api/v1/remote_write"
        }
      },
      "pipelines": {
        "metrics": {
          "amp": {
            "enabled": true
          },
          "emf": {
            "enabled": false
          }
        }
      },
      "serviceAccount": {
        "annotations": {
          "eks.amazonaws.com/role-arn": "arn:aws:iam::xxxxx:role/ADOTCollectorPrometheusRole"
        }
      }
    }
  }
}
```
