### ISSUE TITLE
Allow for configuration of prometheus scrape metrics for ADOT eks addon to be part of the addon configuration  >= 0.88.0

### ISSUE THREAD

**Issue by sastie-rai** [aws-observability/aws-otel-collector#2511]
The current setup does not allow for the prometheus scrape metrics to be provided as part of the addon configuration.
The current way of modifying scrape interval and timeout is through: 
`kubectl -n opentelemetry-operator-system edit opentelemetrycollector adot-col-prom-metrics`

it would be nice to be able to have these configurable as part of the addon config.
```yaml
config:
   receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s
```
