### ISSUE TITLE
ADOT Collector for X-Ray receiver open 2000/TCP port not 2000/UDP

### ISSUE THREAD

**Issue by arron-shin** [aws-observability/aws-otel-collector#2548]
**Describe the bug**

When I create the xray receiver, the adot collector creates a pod with a **tcp 2000 port, not a udp 2000 port**.

```
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  awsxray:
    transport: udp

processors:
  batch:

exporters:
  awsxray:
    region: 'ap-northeast-2'

service:
  pipelines:
    traces:
      receivers: [awsxray]
      exporters: [awsxray]

  extensions: [pprof]
  telemetry:
    logs:
      level: debug
```

**Steps to reproduce**

**What did you expect to see?**
In the case of the X-Ray daemon, I found that the 2000 UDP port was set up just fine.

**What did you see instead?**
aws-otel-collector (v0.35.0) open port 2000/TCP

**Environment**
Amazon EKS v1.28

**Comment by bryan-aguilar** [comment]
If you are running this on EKS you can create a [service](https://kubernetes.io/docs/tutorials/services/connect-applications-service/) to route traffic to with UDP protocol on port 2000 to your ADOT Collector pods.

**Comment by arron-shin** [comment]
@bryan-aguilar It's strange that I have to create a separate service. I think if the user specifies transport as udp in the collector's config, the operator should open port 2000 of that pod as udp.

**Comment by arron-shin** [comment]
I installed the ADOT add-on from the AWS console and confirmed that the operator installation is complete. Afterward, I created a collector related to X-Ray ingest using the following CRD.

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: adot-collector-xray-ingest
  namespace: opentelemetry-operator-system
spec:
  mode: deployment
  resources:
    requests:
      cpu: "1"
    limits:
      cpu: "1"
  serviceAccount: adot-collector-xray
  config: |
    receivers:
      awsxray:
        transport: udp

    processors:
      batch:

    exporters:
      awsxray:
        aws_log_groups: ['/aws/eks/my-eks-cluster/application']
        region: 'ap-northeast-2'

    service:
      pipelines:
        traces:
          receivers: [awsxray]
          exporters: [awsxray]
      telemetry:
        logs:
          level: debug
```

Afterward, a collector resource was created, and here is the description of the service.

```
│ Name:              adot-collector-xray-ingest-collector                                                                                                                              │
│ Namespace:         opentelemetry-operator-system                                                                                                                                     │
│ Labels:            app.kubernetes.io/component=opentelemetry-collector                                                                                                               │
│                    app.kubernetes.io/instance=opentelemetry-operator-system.adot-collector-xray-ingest                                                                               │
│                    app.kubernetes.io/managed-by=opentelemetry-operator                                                                                                               │
│                    app.kubernetes.io/name=adot-collector-xray-ingest-collector                                                                                                       │
│                    app.kubernetes.io/part-of=opentelemetry                                                                                                                           │
│                    app.kubernetes.io/version=latest                                                                                                                                  │
│ Annotations:       <none>                                                                                                                                                            │
│ Selector:          app.kubernetes.io/component=opentelemetry-collector,app.kubernetes.io/instance=opentelemetry-operator-system.adot-collector-xray-ingest,app.kubernetes.io/managed │
│ -by=opentelemetry-operator,app.kubernetes.io/part-of=opentelemetry                                                                                                                   │
│ Type:              ClusterIP                                                                                                                                                         │
│ IP Family Policy:  SingleStack                                                                                                                                                       │
│ IP Families:       IPv4                                                                                                                                                              │
│ IP:                172.20.19.79                                                                                                                                                      │
│ IPs:               172.20.19.79                                                                                                                                                      │
│ Port:              awsxray  2000/TCP                                                                                                                                                 │
│ TargetPort:        2000/TCP                                                                                                                                                          │
│ Endpoints:         10.0.175.19:2000                                                                                                                                                  │
│ Session Affinity:  None                                                                                                                                                              │
│ Events:            <none>
```

My
