### ISSUE TITLE
Collector fails to start with ECS Observer: permission denied

### ISSUE THREAD

**Issue by waynePortrait** [aws-observability/aws-otel-collector#2620]
**Describe the bug**

When starting the collector service on ECS, with the ECS Observer extension enabled (see config) the collector task fails to start with the following error:

```
error ecsobserver@v0.88.0/extension.go:33 ECSDiscovery stopped by error {"kind": "extension", "name": "ecs_observer", "error": "open /etc/ecs_sd_targets.yaml: permission denied"}
```

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

As far as I can tell, simply including the ECS Observer extension in the configuration will recreate the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

I expected ECS service discovery to complete successfully.

**What did you see instead?**
A clear and concise description of what you saw instead.

The error above.

**Environment**
Describe any aspect of your environment relevant to the problem. 
If this is related to a deployment of the ADOT Collector please
provide your Collector config file. 

This is happening for me with versions 0.35.0 and later of the collector.  Versions 0.34.0 and earlier work fine.

My config is based off [this example](https://github.com/aws-samples/ecs-gpu-scaling).  My specific ECS Observer config is below.

```yaml
extensions:
  ecs_observer:
    cluster_name: '<my cluster>'
    cluster_region: 'us-east-1'
    result_file: '/etc/ecs_sd_targets.yaml'
    job_label_name: prometheus_job
    services:
      - name_pattern: ".*Triton.*"
        container_name_pattern: "triton"
        metrics_ports:
          - 8002
```

**Additional context**

As noted, this error happens for me with versions 0.35.0 and later.  I discovered the problem when, after following the linked example, I tried updating the collector version from the very old 0.11.0 it uses to `latest`.  The image declaration in the example has [a comment](https://github.com/aws-samples/ecs-gpu-scaling/blob/main/lib/ecs-gpu-demo-stack.ts#L239) to a now-resolved issue that appears to be unrelated, so I didn't think this would be a problem.  When it was, I started trying specific earlier versions until I found the latest that would work for me.
