### ISSUE TITLE
Do ADOT collector (Prometheus Receiver) supports Prometheus Web UI?

### ISSUE THREAD

**Issue by jatinmehrotra** [aws-observability/aws-otel-collector#2645]
**Describe the question**

- I am using ADOT collector + AMP + Grafana for observing metrics for my EKS cluster. I want to know if Is it possible there is an extension /configuration supported for the ADOT collector for collecting Prometheus metrics.

- Prometheus server publishes some metrics (like to determine the cost), is it even possible to publish metrics from ADOT collector. I am aware that same metrics is not possible but equivalent metrics if exposed by collector.

**Steps to reproduce if your question is related to an action**

I am using the sample config provided by adot team docs

```
config: |
    receivers:
      #
      # Scrape configuration for the Prometheus Receiver
      # This is the same configuration used when Prometheus is installed using the community Helm chart
      #
      prometheus:
        config:
          global:
            scrape_interval: 10s
            scrape_timeout: 10s
            
            ......
```

**What did you expect to see?**

I want to enable Prometheus Web UI for the ADOT collector

**Environment**
Describe any aspect of your environment.
If this is related to a deployment of the ADOT Collector please
provide your Collector config file. 

```

apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  mode: deployment
  serviceAccount: ${service_account_name}
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8888'
  resources:
    limits:
      cpu: 1
      memory: 4G
    requests:
      cpu: 1
      memory: 4G
  config: |
    receivers:
      #
      # Scrape configuration for the Prometheus Receiver
      # This is the same configuration used when Prometheus is installed using the community Helm chart
      #
      prometheus:
        config:
          global:
            scrape_interval: 10s
            scrape_timeout: 10s

          scrape_configs:
          - job_name: kubernetes-nodes-cadvisor
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
            - role: node
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - replacement: kubernetes.default.svc:443
              target_label: __address__
            - regex: (.+)
              replacement: /api/v1/nodes/$$1/proxy/metrics/cadvisor
              source_labels:
              - __meta_kubernetes_node_name
              target_label: __metrics_path__
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true

          - job_name: my-service-monitoring
            scrape_interval: 10s
            kubernetes_sd_configs:
              - roles: sub
            relabel_configs:
              - action: keep
                regex: xxx-cs;(9090|9121)
                source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_container_port_number
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_container_name
                target_label: container_name
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_name
                target_label: pod_name

    processors:
      batch/metrics:
        timeout: 60s

    exporters:
      prometheusremotewrite:
        endpoint: ${amp_workspace_endpoint}
        auth:
          authenticator: sigv4auth

    extensions:
      sigv4auth:
        service: "aps"
        region: ${region}
        assume_role:
          arn: ${role_arn}

    service:
      extensions: [sigv4auth]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch/metrics]
          exporters: [prometheusremotewrite]
```

**Additional context**

https://github.com/aws-observability/aws-otel-collector/issues/2463

I have see a similar issue which is somehow related to which there is no update so far.
