### ISSUE TITLE
 err: open /opt/aws/aws-otel-collector/etc/extracfg.txt: no such file or directory

### ISSUE THREAD

**Issue by jyoti-enya** [aws-observability/aws-otel-collector#2736]
Team, I am using CF templates to add observability . The ECS Task is running on ecs ec2

```
        - Name: "aws-otel-emitter"
          Image: app-image:v1.6.3
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "true"
              awslogs-group: "/ecs/aws-otel-emitter"
              awslogs-region: "us-east-2"
              awslogs-stream-prefix: "ecs"
          DependsOn:
            - ContainerName: "aws-otel-collector"
              Condition: "START"
          MemoryReservation: 128
        - Name: "aws-otel-collector"
          Image: "public.ecr.aws/aws-observability/aws-otel-collector:stable"
          Essential: true
          Environment:
            - Name: "AWS_PROMETHEUS_ENDPOINT"
              Value: "url"
            - Name: "AWS_PROMETHEUS_SCRAPING_ENDPOINT"
              Value: "0.0.0.0:7300"              
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "True"
              awslogs-group: "/ecs/ecs-aws-otel-sidecar-collector"
              awslogs-region: "us-east-2"
              awslogs-stream-prefix: "ecs"
          MemoryReservation: 128
```

I am seeing this error in console 

```
Task is stopping
Task failed to start
```

Can someone help here please?
