### ISSUE TITLE
AWS Distro for OpenTelemetry EKS add-on for kubernetes 1.30?

### ISSUE THREAD

**Issue by rgl** [aws-observability/aws-otel-collector#2745]
**Describe the question**

EKS is now supporting and suggesting upgrades to Kubernetes 1.30, but the AWS Distro for OpenTelemetry EKS add-on is not supported.

Any idea/milestone when it will available?

**Steps to reproduce if your question is related to an action**

Launch an EKS instance with Kubernetes 1.30, then try to add the add-on, you'll not be able due to:

![image](https://github.com/aws-observability/aws-otel-collector/assets/43356/41cc3685-5afc-4e0c-aec6-84db88e6b6c5)

**What did you expect to see?**

I expected to use the add-on with EKS 1.30.

**Comment by clementlecorre** [comment]
No news?

**Comment by catomatik** [comment]
Has anyone found the reason why the add-on is not supported?
Btw, if it was installed, it remains functional with version 1.30, but you cannot manage it as an EKS add-on anymore.

**Comment by gavinjohnson-crowdcube** [comment]
Just bumped into this one yesterday when trying to install it in a 1.30 cluster.

**Comment by sonalita** [comment]
I have also hit this issue when trying to upgrade addons to 1.30

**Comment by sonalita** [comment]
See also https://github.com/aws/containers-roadmap/issues/2365

**Comment by vsakaram** [comment]
just a quick note, we plan to address this soon and we will keep this ticket updated

**Comment by zmully** [comment]
@vsakaram any update on when 1.30 support will be available? 

It's been **_75 days_** since EKS 1.30 was released, and I'm sure everyone watching this ticket certainly didn't expect it to take this long. Your 0.92 release trailed EKS 1.29 by 22 days, which still isn't great, but this is getting out of hand. With the next EKS release (1.31) expected in the next couple months, the ADOT release cadence really needs attention. This has hamstrung our ability to track the most recent EKS releases, and is actively undermining our trust in AWS's ability to provide a robust ecosystem of services and tooling.

**Comment by sidick** [comment]
> @vsakaram any update on when 1.30 support will be available?
> 
> It's been **_75 days_** since EKS 1.30 was released, and I'm sure everyone watching this ticket certainly didn't expect it to take this long. Your 0.92 release trailed EKS 1.29 by 22 days, which still isn't great, but this is getting out of hand. With the next EKS release (1.31) expected in the next couple months, the ADOT release cadence really needs attention. This has hamstrung our ability to track the most recent EKS releases, and is actively undermining our trust in AWS's ability to provide a robust ecosystem of services and tooling.

I agree, this is making me reconsider using the EKS addon and moving to self managed helm charts as it seems they're maintained better and at least aren't tied to particular EKS versions

**Comment by clementlecorre** [comment]
I used an alternative solution to avoid using the Opentelemetry add-on by directly utilizing the CloudWatch Agent (https://docs.aws.amazon.com/eks/latest/userguide/amazon-cloudwatch-observability.html), which also allows pushing traces to X-Trace.

I added the annotation for automatic configuration on my Java applications:

```yaml
Annotations:
    instrumentation.opentelemetry.io/inject-java: true
```

This injects the agent directly as well as the configuration of the `OTEL_` environment variables:

```yaml
    OTEL_AWS_APP_SIGNALS_ENABLED:                    true
    OTEL_AWS_APPLICATION_SIGNALS_ENABLED:            true
    OTEL_TRACES_SAMPLER_ARG:                         endpoint=http://cloudwatch-agent.amazon-cloudwatch:2000
    OTEL_TRACES_SAMPLER:                             xray
    OTEL_EXPORTER_OTLP_PROTOCOL:                     http/protobuf
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:              http://cloudwatch-agent.amazon-cloudwatch:4316/v1/traces
    OTEL_AWS_APP_SIGNALS_EXPORTER_ENDPOINT:          http://cloudwatch-agent.amazon-cloudwatch:4316/v1/metrics
    OTEL_AWS_APPLICATION_SIGNALS_EXPORTER_ENDPOINT:  http://cloudwatch-agent.amazon-cloudwatch:4316/v1/metrics
    OTEL_METRICS_EXPORTER:                           none

....
```
I used an alternative solution while waiting for support for this add-on
