### ISSUE TITLE
aws_cloud_map resolver not working for loadbalancing exporter

### ISSUE THREAD

**Issue by mburisa-glooko** [aws-observability/aws-otel-collector#2784]
**Describe the question**
I'm using `aws-otel-collector:v0.40.0` inside AWS ECS cluster with gateway architecture approach. my first tier collectors are running as exporters sending grouped traces to my second tier collectors running sampling and filtering. 
my issue is with the **aws_cloud_map** resolver on first-tier

I'm getting the following error
```2024-07-31T09:29:33.623Z warn loadbalancingexporter@v0.102.0/resolver_aws_cloudmap.go:144 failed to resolve {"kind": "exporter", "data_type": "traces", "name": "loadbalancing", "resolver": "aws_cloud_map", "error": "operation error ServiceDiscovery: DiscoverInstances, https response error StatusCode: 400, RequestID: fd31e9f2-9578-4984-ad18-7675c2947da0, NamespaceNotFound: Namespace not found"}```

it's not a permission issue as that has been resolved. both namespace (named `mb-namespace.local` and service (named `sumologic-second-tier` exist) in that VPC and ECS cluster

**if I use static resolver everything works but that won't work with scaling**

**Steps to reproduce if your question is related to an action**
Relevant part of configuration:

```yaml
exporters:
  loadbalancing:
    routing_key: "service"
    protocol:
      otlp:
        compression: gzip
        timeout: 1s
        tls:
          insecure: true # certificate does not have IP SANs
          insecure_skip_verify: true
    resolver:
      #static:
      #  hostnames:
      #  - 10.140.1.49:4317
      #  - 10.140.1.72:4317
      #  - 10.140.3.53:4317
      aws_cloud_map:
        namespace: mb-namespace.local
        service_name: sumologic-second-tier
        interval: 30s
        timeout: 5s
```

**What did you expect to see?**
All X ECS tasks/container instances are resolved using aws_cloud_map resolver and traces exporter to those collectors

**Environment**
I've checked on the ECS with aws cli - permissions are fine and using `servicediscovery describe-instances` API call they are listed as expected

```bash
$ aws servicediscovery list-namespaces
{
    "Namespaces": [
        {
            "Id": "ns-XXXX",
            "Arn": "arn:aws:servicediscovery:eu-west-1:XXXX:namespace/ns-XXXX",
            "Name": "mb-namespace.local",
            "Type": "DNS_PRIVATE",
            "Description": "ecs",
            "Properties": {
                "DnsProperties": {
                    "HostedZoneId": "XXXXX",
                    "SOA": {
                        "TTL": 15
                    }
                },
                "HttpProperties": {
                    "HttpName": "mb-namespace.local"
                }
            },
            "CreateDate": "2023-03-16T20:02:05.166000+00:00"
        },
```

```bash
$ aws servicediscovery discover-instances --namespace mb-namespace.local --service-name sumologic-second-tier
{
    "Instances": [
        {
            "InstanceId": "fdd68915ab534b74b8271a049aa81e4a",
            "NamespaceName": "mb-namespace.local",
            "ServiceName": "sumologic-second-tier",
            "HealthStatus": "HEALTHY",
            "Attributes": {
                "AVAILABILITY_ZONE": "eu-west-1c",
                "AWS_INIT_HEALTH_STATUS": "HEALTHY",
                "AWS_INSTANCE_IPV4": "10.140.1.49",
                "AWS_INSTANCE_PORT": "4317",
                "EC2_INSTANCE_ID": "i-095583289axxxx",
                "ECS_CLUSTER_NAME": "mb",
                "ECS_SERVICE_NAME": "sumologic-second-tier-otel-service",
                "ECS_TASK_DEFINITION_FAMILY": "mb-sumologic-second-tier-otel-collector",
                "REGION": "eu-west-1"
            }
        },
        {
            "InstanceId": "c2107da456c44929aecaf807c1c1c36f",
            "NamespaceName": "mb-namespace.local",
            "ServiceName": "sumologic-second-tier",
            "HealthStatus": "HEALTHY",
            ...
...
...
```

**Additional context**
