### ISSUE TITLE
OTEL Fargate Container Insights configuration does not define a namespace or service account

### ISSUE THREAD

**Issue by janrito** [aws-observability/aws-otel-collector#2824]
**Describe the bug**
Following [this guide](https://aws-otel.github.io/docs/getting-started/container-insights/eks-fargate)
 
[deployment-template/eks/otel-fargate-container-insights.yaml](https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/otel-fargate-container-insights.yaml)

does not define a namespace or a service account - fails to deploy

```
namespaces "fargate-container-insights" not found
```

Should be:
```yamlapiVersion: v1
kind: Namespace
metadata:
  name: fargate-container-insights
  labels:
    name: fargate-container-insights
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: fargate-container-insights
---
kind: ClusterRole
...
```
