### ISSUE TITLE
OTEL Fargate Container Insights is not authenticated

### ISSUE THREAD

**Issue by janrito** [aws-observability/aws-otel-collector#2825]
**Describe the bug**
Following [this guide](https://aws-otel.github.io/docs/getting-started/container-insights/eks-fargate).

It seems like the collector does not receive the necessary permissions to push metrics out:

Have created a `adot-collector` service account in the namespace `fargate-container-insigts` and attached it to a role with the permissions `arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy`

Have deployed the collector using https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/otel-fargate-container-insights.yaml
changed the cluster name and regions to the correct ones
also added the namespace definition and service account (related #2824):

```
kind: Namespace
metadata:
  name: fargate-container-insights
  labels:
    name: fargate-container-insights
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: fargate-container-insights
---
kind: ClusterRole
...
```

Still the collector cannot send metrics.

```json
{
    "log": "2024-09-05T16:52:42.790552892Z stderr F 2024-09-05T16:52:42.790Z\twarn\tbatchprocessor@v0.102.1/batch_processor.go:263\tSender failed\t{\"kind\": \"processor\", \"name\": \"batch\", \"pipeline\": \"metrics\", \"error\": \"NoCredentialProviders: no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\"}"
}
```

Incidentally, this documentation is quite sparse and challenging to follow. What I'm trying to achieve is relatively simple in ECS, but has been quite a challenge in EKS: Container Insights on Fargate
