### ISSUE TITLE
v.0.41.x version of aws-otel-collector incorporates Open Telemetry Collector Bug: https://github.com/open-telemetry/opentelemetry-collector/issues/11239 

### ISSUE THREAD

**Issue by pawelkaliniakit** [aws-observability/aws-otel-collector#2881]
**Describe the bug**
Version 0.41.x of aws-otel-collector has following dependency:

OpenTelemetry Collector dependencies to v1.15.0/v0.109.0

and the dependency v0.109.0 has following issue:
https://github.com/open-telemetry/opentelemetry-collector/issues/11239

that has been solved in v.110.0 of the dependency

**Steps to reproduce**
Try to scrap prometheus endpoint with the v.0.41.x aws-otel-collector

**What did you expect to see?**
No issues in collector log while scrapping the prometheus endpoint

**What did you see instead?**
```
2024/10/16 10:19:16 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request.(*RespWriterWrapper).writeHeader (resp_writer_wrapper.go:78)
```
in logs of the collector

**Environment**

part of config
```
  prometheus/something:
    config:
      global:
        scrape_interval: 5m
        scrape_timeout: 10s
      scrape_configs:
        - job_name: "something-something"
          static_configs:
            - targets: [0.0.0.0:9465]
```
