### ISSUE TITLE
Timeline for ADOT EKS Addon for Kubernetes 1.32?

### ISSUE THREAD

**Issue by cizzo-raidbase** [aws-observability/aws-otel-collector#2960]
**Describe the question**
EKS now supports Kubernetes 1.32 but the ADOT EKS Addon currently supports up to Kubernetes 1.31. Is there a specific timeline to expect as to when the ADOT EKS Addon may see support for Kubernetes 1.32?

**Steps to reproduce if your question is related to an action**
```
aws eks describe-addon-versions --addon-name adot --kubernetes-version 1.32
```

Returns no supported addons

**What did you expect to see?**
`adot` supporting Kubernetes 1.32

**Environment**
n/a

**Additional context**
n/a

**Comment by mhausenblas** [comment]
Thanks for reaching out @cizzo-raidbase and just to confirm: we're working on it. DfD for an update on the timeline is end of next week.

**Comment by henkka** [comment]
Any news on what's causing these issues every time a new EKS version is released? We're once again blocked from upgrading to EKS 1.32, similar to what happened with the previous two or three version upgrades. :/

**Comment by mhausenblas** [comment]
@henkka we're working on it

**Comment by BensamViswambharan** [comment]
We are blocked with the eks 1.32 upgrade.. do we have a timeline?

**Comment by subhasisraysophos** [comment]
Any news here? Please share us a timeline

**Comment by mhausenblas** [comment]
Thanks for your patience. While I can not share a definitive timeline, I wanted to update the thread with a bit of context: as a prerequisite to the add-on we have to release a new ADOT collector version. This is currently delayed due to a [recent Go CVE](https://groups.google.com/g/golang-announce/c/7Xy3Zn0nlk4/m/AYzGnOghAAAJ?pli=1).

**Comment by subhasisraysophos** [comment]
Still waiting for a compatible version. Can you please let us know any status on the progress here?

**Comment by mhausenblas** [comment]
@subhasisraysophos you can track the progress via https://github.com/aws-observability/aws-otel-collector/pulls where you can see the work towards a new ADOT collector release. Once that is done, we can cut a new add-on release.

**Comment by henkka** [comment]
The provided GitHub pull request view is a bit challenging to follow, as I'm not sure which specific PRs are relevant to the upcoming release. If possible, could you kindly point me to the key PRs we're waiting on, or share any information about the expected timeline?

**Comment by skolenkin-lumen** [comment]
Do you have any updates?

**Comment by venkateswarlu-vajrala-fs-vv** [comment]
Any updates ? We are blocked without adot version. Also it seems this is happening for every k8s release version. Is there a plan to mitigate this issue again in future version?

**Comment by sidick** [comment]
> We have Kubernetes new version 1.33 released as well, https://kubernetes.io/blog/2025/04/23/kubernetes-v1-33-release/ . When we should expect this to get complete. Kindly provide any update on this.

At this stage I'm hoping they make the next version able to work on 1.33 at the same time even if it's not out on EKS yet

**Comment by bdlilley** [comment]
@mhausenblas  can you give us an update on this? This kind of blows my mind - the public helm chart repo is deprecated, there are zero docs on how to install without the addon - all docs go back to "install via the addon". If it cannot be released in a timely manner, please revive the public helm chart repo so the community can submit PRs to keep the trains on the track.

**Comment by bdlilley** [comment]
For those that find this issue seeking a solution - here is my conclusion:

1. Use `aws-otel-collector` for container insights metrics ONLY (not for logging) for two reasons:
  - it works for metrics insights with minimal config
  - awscloudwatchlogs is mostly not useful due to missing features, for example you cannot dynamically name log groups or streams - for any real installation this is a deal-breaker, so don't rely on aws-otel-collector for logs
    - to be clear, even if AWS released this addon for 1.32 and 1.33, it would still not be a good logging solution for the reasons stated
2. Use [fluent-for-aws](https://github.com/aws/aws-for-fluent-bit) for logging
  - feature-rich and flexible - for example dynamic log group names and easy workload filtering
  - config isn't too hard to set up

### Example: logs with fluent-for-aws

```bash
helm repo add eks https://aws.github.io/eks-charts
helm repo update
```

Sample values.yaml (**note: us-east-2 and limited to sample|other-ns namespaces; adjust to your needs**):

```yaml
cloudWatchLogs:
  enabled: true
  match: "kube.*"
  region: "us-east-2"
  logGroupTemplate: /aws/eks/dev-eks-api/logs/$kubernetes['namespace_name']
  logStreamTemplate: $kubernetes['pod_name'].$kubernetes['container_name']
  autoCreateGroup: true

filter:
  enabled: true
  match: "kube.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "On"
  mergeLogKey: "data"
  keepLog: "On"
  k8sLoggingParser: "On"
  k8sLoggingExclude: "On"
  bufferSize: "32k"
  kubeTagPrefix: "application.var.log.containers."
  regexParser: "kube-tag"

additionalFilters: |
  [FILTER]
      Name   grep
      Match  kube.*
      Regex  $kubernetes['namespace_name'] (sample|other-ns)
```

```bash
helm upgrade -i fluent-for-aws eks/aws-for-fluent-bit -n logging --create-namespace -f values.yaml
```

### Example: container insights with aws-otel-collector

Apply the manifest in this repo https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/otel-container-insights-infr

You need to update the config with at least your cluster name b/c `{ClusterName}` does not appear to work. Here is the example with cluster name "dev-eks-api". Also don't forget region - in this example it's us-east-2.

```yaml
# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: aws-otel-eks
  labels:
    name: aws-otel-eks

---
# create cwagent service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-otel-sa
  namespace: aws-otel-eks

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aoc-agent-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "endpoints"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes/stats", "configmaps", "events"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["otel-container-insight-clusterleader"]
    verbs: ["get", "update", "create"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["otel-container-insight-clusterleader"]
    verbs: ["get", "update", "create"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aoc-agent-role-binding
subjects:
  - kind: ServiceAccount
    name: aws-otel-sa
    namespace: aws-otel-eks
roleRef:
  kind: ClusterRole
  name: aoc-agent-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  namespace: aws-otel-eks
  labels:
    app: opentelemetry
    component: otel-agent-conf
data:
  otel-agent-config: |
    extensions:
      health_check:

    receivers:
      awscontainerinsightreceiver: {}

    processors:
      batch/metrics:
        timeout: 60s

    exporters:
      awsemf:
        namespace: ContainerInsights
        log_group_name: '/aws/containerinsights/dev-eks-api/performance'
        region: us-east-2
        log_stream_name: '{NodeName}'
        resource_to_telemetry_conversion:
          enabled: true
        dimension_rollup_option: NoDimensionRollup
        parse_json_encoded_attr_values: [Sources, kubernetes]
        metric_declarations:
          # node metrics
          - dimensions: [[NodeName, InstanceId, ClusterName]]
            metric_name_selectors:
              - node_cpu_utilizationf
              - node_memory_utilization
              - node_network_total_bytes
              - node_cpu_reserved_capacity
              - node_memory_reserved_capacity
              - node_number_of_running_pods
              - node_number_of_running_containers
          - dimensions: [[ClusterName]]
            metric_name_selectors:
              - node_cpu_utilization
              - node_memory_utilization
              - node_network_total_bytes
              - node_cpu_reserved_capacity
              - node_memory_reserved_capacity
              - node_number_of_running_pods
              - node_number_of_running_containers
              - node_cpu_usage_total
              - node_cpu_limit
              - node_memory_working_set
              - node_memory_limit

          # pod metrics
          - dimensions: [[PodName, Namespace, ClusterName], [Service, Namespace, ClusterName], [Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - pod_cpu_utilization
              - pod_memory_utilization
              - pod_network_rx_bytes
              - pod_network_tx_bytes
              - pod_cpu_utilization_over_pod_limit
              - pod_memory_utilization_over_pod_limit
          - dimensions: [[PodName, Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - pod_cpu_reserved_capacity
              - pod_memory_reserved_capacity
          - dimensions: [[PodName, Namespace, ClusterName]]
            metric_name_selectors:
              - pod_number_of_container_restarts

          # cluster metrics
          - dimensions: [[ClusterName]]
            metric_name_selectors:
              - cluster_node_count
              - cluster_failed_node_count

          # service metrics
          - dimensions: [[Service, Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - service_number_of_running_pods

          # node fs metrics
          - dimensions: [[NodeName, InstanceId, ClusterName], [ClusterName]]
            metric_name_selectors:
              - node_filesystem_utilization

          # namespace metrics
          - dimensions: [[Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - namespace_number_of_running_pods

    service:
      pipelines:
        metrics:
          receivers: [awscontainerinsightreceiver]
          processors: [batch/metrics]
          exporters: [awsemf]
      extensions: [health_check]

---
# create Daemonset
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-otel-eks-ci
  namespace: aws-otel-eks
spec:
  selector:
    matchLabels:
      name: aws-otel-eks-ci
  template:
    metadata:
      labels:
        name: aws-otel-eks-ci
    spec:
      containers:
        - name: aws-otel-collector
          image: public.ecr.aws/aws-observability/aws-otel-collector:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: Always
          command:
            - "/awscollector"
            - "--config=/conf/otel-agent-config.yaml"
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: containerdsock
              mountPath: /run/containerd/containerd.sock
            - name: varlibdocker
              mountPath: /var/lib/docker
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: devdisk
              mountPath: /dev/disk
              readOnly: true
            - name: otel-agent-config-vol
              mountPath: /conf
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
        - configMap:
            name: otel-agent-conf
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml
          name: otel-agent-config-vol
        - name: rootfs
          hostPath:
            path: /
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker
        - name: containerdsock
          hostPath:
            path: /run/containerd/containerd.sock
        - name: sys
          hostPath:
            path: /sys
        - name: devdisk
          hostPath:
            path: /dev/disk/
      serviceAccountName: aws-otel-sa
```
