### ISSUE TITLE
How to configure the healthcheck in ECS Fargate for multiple Otel collectors in one task

### ISSUE THREAD

**Issue by marcus-eder** [aws-observability/aws-otel-collector#3016]
We are trying to configure a Otel collector service composed of several chained Otel collectors. We use a mixture of Adot and contrib collectors. They are all defined in one taskdefinition

Now we struggle with the healthcheck. 

We know that we need to configure a different port for each collector, like

```yaml
extensions:
  health_check:
    endpoint: 0.0.0.0:13134  # Changed to a non-standard port

```

Now our question is, how can we tell ECS to do the healthcheck on the right port, since we only configure

```yaml
"healthCheck": {
                "command": [
                    "/healthcheck"
                ],
                "interval": 5,
                "timeout": 6,
                "retries": 5,
                "startPeriod": 1
            },

```

Thanks for your reply
