### ISSUE TITLE
NoCredentialProviders: no valid providers in chain

### ISSUE THREAD

**Issue by weklund** [aws-observability/aws-otel-collector#3036]
(I realize there's a few issues on [this theme](https://github.com/aws-observability/aws-otel-collector/issues?q=is%3Aissue%20state%3Aclosed%20NoCredentialProviders%3A%20no%20valid%20providers%20in%20chain), so forgive the duplication, but I'm still having an issue, so I would love guidance on debugging)

**Describe the bug**
I have docker compose setup on an ubuntu machine.  I'm trying to send test traces so I can view in xray.  It seems erroring saying no valid credentials.  I've tried a combination of passing AWS_PROFILE and AWS_REGION and AWS_ACCESS_KEY and AWS_SECRET_KEY (I would prefer not to) and both fail.

I have also double checked on the host machine and other containers that need AWS creds and they work fine.

On the host machine I'm running:
```
curl -X POST -H "Content-Type: application/json" -d @test-trace.json http://localhost:4318/v1/traces
```

Then I retrieve the docker logs via `docker logs adot-collector`

```
2025-05-13T04:15:28.460Z	error	internal/base_exporter.go:128	Exporting failed. Rejecting data.	{"kind": "exporter", "data_type": "traces", "name": "awsxray", "error": "NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors", "rejected_items": 1}
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Send
	go.opentelemetry.io/collector/exporter@v0.117.0/exporterhelper/internal/base_exporter.go:128
go.opentelemetry.io/collector/exporter/exporterhelper.NewTracesRequest.func1
	go.opentelemetry.io/collector/exporter@v0.117.0/exporterhelper/traces.go:136
go.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces
	go.opentelemetry.io/collector/consumer@v1.23.0/traces.go:26
go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).export
	go.opentelemetry.io/collector/processor/batchprocessor@v0.117.0/batch_processor.go:447
go.opentelemetry.io/collector/processor/batchprocessor.(*shard[...]).sendItems
	go.opentelemetry.io/collector/processor/batchprocessor@v0.117.0/batch_processor.go:261
go.opentelemetry.io/collector/processor/batchprocessor.(*shard[...]).startLoop
	go.opentelemetry.io/collector/processor/batchprocessor@v0.117.0/batch_processor.go:221
2025-05-13T04:15:28.460Z	warn	batchprocessor@v0.117.0/batch_processor.go:263	Sender failed	{"kind": "processor", "name": "batch", "pipeline": "traces", "error": "NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
```

Here's my docker-compose.yml
```
adot: 
    container_name: adot-collector
    image: public.ecr.aws/aws-observability/aws-otel-collector:v0.43.2 # Use latest stable or a specific recent version
    volumes:
      - ./adot/collector-config.yaml/collector-config.yaml:/etc/otel/config.yaml:ro # Corrected path
      - /:/hostfs:ro  # Mount the host filesystem as read-only # Keep if using hostmetrics specific to underlying host
      - ~/.aws/config:/home/aoc/.aws/config:ro
      - ~/.aws/credentials:/home/aoc/.aws/credentials:ro
    environment:
      - AWS_PROFILE=default
      - AWS_REGION=us-east-2
      - AWS_SDK_LOAD_CONFIG=1
      - AWS_CONFIG_FILE=/home/aoc/.aws/config
      - AWS_SHARED_CREDENTIALS_FILE=/home/aoc/.aws/credentials
    ports:
      - "4317:4317"   
      - "4318:4318"   
      - "8888:8888"   
      - "2000:2000"   
    command: ["--config=/etc/otel/config.yaml"]
    restart: unless-stopped
    networks:
      - my-network

```

collector-config.yml
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  # hostmetrics: # This collects metrics from the machine where the collector is running.
  #   collection_interval: 60s # Increased interval to reduce load/cost slightly
  #   scrapers:
  #     cpu:
  #     memory:
  #     disk:
  #     # filesystem: # Can be noisy; enable if specifically needed
  #     network:
  #     load:
  #     # paging: # Enable if needed
  #     # process: # Can be very verbose; enable if needed for specific process metrics on the collector host
  #     #   metrics:
  #     #     process.cpu.utilization:
  #     #       enabled: true

processors:
  batch:
    timeout: 1s # Default is 1s, good.
    send_batch_size: 1024 # Default is 8192. 1024 is smaller, might send more frequently. Adjust based on load.
  # Memory limiter is crucial for production to prevent OOM errors
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75 # Percentage of total RAM available to the container/host
    spike_limit_percentage: 15

exporters:
  awsxray:
    region: "us-east-2"
    # For better searchability in X-Ray, specify attributes to index.
    # Semantic conventions for HTTP, AWS SDK, RPC are good candidates.
    indexed_attributes:
      - http.method
      - http.url
      - http.status_code
      - http.target
      - aws.s3.bucket # Example if you have S3 calls
      - rpc.service
      - rpc.method
    # To propagate trace context to AWS SDK calls made BY THE COLLECTOR (rare for xray exporter, but good practice for others)
    # aws_sdk:
    #   region: "us-east-2" # Or ensure the collector's environment has AWS_REGION

  awsemf: # For metrics to CloudWatch Embedded Metric Format
    region: "us-east-2"
    namespace: "ModusApp" # Consistent namespace
    # metric_declarations: # Optional: for specific metric transformations, units, dimensions
    #   - dimensions: [[InstanceId, host.id], [ClusterName]] # Example dimensions
    #     metric_name_selectors: ["^system.cpu*"]
    log_group_name: "/aws/otel/application-metrics" # Customize log group for EMF metrics if needed
    log_stream_name: "otel-stream-{TaskID}" # Customize log stream if needed
    resource_to_telemetry_conversion: # Useful for adding resource attributes as dimensions
      enabled: true


# (Optional) For X-Ray Remote Sampling:
# extensions:
#   awsxrayremote_sampler:
#     region: "us-east-2" # Region for sampling rules
#     # role_arn: "arn:aws:iam::ACCOUNT_ID:role/OtelCollectorXRaySamplingRole" # If using a specific role
#     polling_interval: "60s" # How often to poll for new sampling rules
#     endpoint: "0.0.0.0:2000" # Endpoint for applications to fetch sampling decisions

service:
  extensions: [] # Add awsxrayremote_sampler here if using
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch] # Add memory_limiter
      exporters: [awsxray]
    # metrics: # Example for host metrics from the collector itself
    #   receivers: [hostmetrics]
    #   processors: [memory_limiter, batch]
    #   exporters: [awsemf]
  # telemetry: # For collector's own metrics (optional, but good for monitoring the collector)
  #   metrics:
  #     address: 0.0.0.0:8888
```

policy on the instance role used
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "cloudwatch:PutMetricData",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:log-group:/python-app/*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "ssm:GetParameter",
                "ssm:GetParameters",
                "ssm:PutParameter",
                "xray:GetSamplingRules",
                "xray:GetSamplingStatisticSummaries",
                "xray:GetSamplingTargets",
                "xray:PutTelemetryRecords",
                "xray:PutTraceSegments"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```

test-trace.json
```
{
    "resource_spans": [
      {
        "resource": {
          "attributes": [
            {"key": "service.name", "value": {"stringValue": "manual-test-service"}},
            {"key": "telemetry.sdk.language", "value": {"stringValue": "manual"}},
            {"key": "telemetry.sdk.version", "value": {"stringValue": "1.0.0"}}
          ]
        },
        "scope_spans": [
          {
            "scope": {"name": "my.manual.instrumentation", "version": "0.1.0"},
            "spans": [
              {
                "trace_id": "0102030405060708090a0b0c0d0e0f10",
                "span_id": "a1a2a3a4a5a6a7a8",
                "name": "manual-test-span",
                "kind": "SPAN_KIND_INTERNAL",
                "start_time_unix_nano": "1715400000000000000", 
                "end_time_unix_nano": "1715400001000000000",   
                "attributes": [
                  {"key": "test.attribute", "value": {"stringValue": "hello-xray"}}
                ],
                "status": {"code": "STATUS_CODE_OK"}
              }
            ]
          }
        ]
      }
    ]
  }
```

**Steps to reproduce**
Run 
````
curl -X POST -H "Content-Type: application/json" -d @test-trace.json http://localhost:4318/v1/traces
````

then look at logs
```
docker logs adot-collector
```

**What did you expect to see?**
A success log I'm assuming?  Also expected to see the trace in xray console.

**What did you see instead?**
A error message and no trace in xray

**Environment**
Host machine: Ubuntu 24.10 (GNU/Linux 6.11.0-21-generic x86_64)
ADOT Image: public.ecr.aws/aws-observability/aws-otel-collector:v0.43.2

My setup is running ADOT on an ubuntu box that's onprem and using Systems Manager Hybrid Activation, so I'm assuming the hybrid activation instance role and having that as the default profile on the box.  The creds rotate every 30 minutes so passing in the access/secret isn't really feasible (and obv security things)
