### ISSUE TITLE
[EMF exporter]Wired dimension when using StatsD receiver and EMF exporter

### ISSUE THREAD

**Issue by gavindoudou** [aws-observability/aws-otel-collector#309]
I used this repo: https://github.com/open-telemetry/opentelemetry-collector-contrib
Here is my config file: 
```
receivers:
  statsd:
    endpoint: "0.0.0.0:55690"
    aggregation_interval: 10s
exporters:
  awsemf:
    namespace: 'StatsD-receiver-test'
    region: 'us-west-2'
    log_group_name: 'aoc-emf-ecs-test-0125'
    log_stream_name: 'aoc-emf-ecs-test-0125'
  logging:
    loglevel: debug
service:
  pipelines:
    metrics:
      receivers: [statsd]
      exporters: [awsemf, logging]
```
Local send one metric: `echo "statsdTestMetric1:2|g|#mykey:myvalue" | nc -w 1 -u localhost 55690`
The EMF log shows like this(the dimension looks strange): 
![image](https://user-images.githubusercontent.com/31523962/105877413-d196b900-5fb4-11eb-88b2-4d37290a35db.png)
I also tested with our AOC image with StatsD component which got the same result: https://hub.docker.com/layers/134376134/gavindoudou/aocrepo/jan22/images/sha256-7a196a8d07b6c81e9cbd08977a9303cef8668a58fdf8834f2ada40b1b21332a5?context=explore
If I input two labels, it will be like this: 
![image](https://user-images.githubusercontent.com/31523962/105877739-25a19d80-5fb5-11eb-97f2-46ee3376ffeb.png)
It may be fine seeing in the log, but if we use the test framework, it shows like this: 
![image](https://user-images.githubusercontent.com/31523962/105886142-e4ae8680-5fbe-11eb-8b0b-51907399295c.png)
It means the validator generated empty dimension metrics does not see in the CloudWatch console

Can anyone please take a look since we plan to merge the StatsD receiver to the AOC this week?
