### ISSUE TITLE
[bug] Config error should return exit code 1

### ISSUE THREAD

**Issue by pingleig** [aws-observability/aws-otel-collector#340]
## Behaviour

If you give an invalid config (e.g. malformed json), the container exit with 0 and  without any error in standard output due to  #339 .
This is a very frustrating experience util you switch to otelcol or otelcontribcol .... 

## Reproduce

```yaml
version: "2"
services:
  aoc:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: [ "--config=/etc/otel-agent-config.yaml", "--log-level=DEBUG" ]
    environment:
      - AWS_REGION=us-west-2
    volumes:
      - ./otel-invalid.yaml:/etc/otel-agent-config.yaml
```

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "static"
            # NOTE: the indent here is WRONG
            static_configs:
              - targets: [ 'localhost:8888' ] # self metric
                labels:
                  foo: bar
        - job_name: "task_def_1"
          file_sd_configs:
            - files:
                - '/etc/ecs_sd_targets.yaml'
exporters:
  awsemf:

service:
  pipelines:
    metrics:
    receivers: [ prometheus ]
    exporters: [ awsemf ]
```

```text
docker-compose up
Recreating config-error_aoc_1 ... done
Attaching to config-error_aoc_1
aoc_1  | AWS OTel Collector version: v0.7.0
aoc_1  | 2021/02/04 04:37:34 find no extra config, skip it, err: open /opt/aws/aws-otel-collector/etc/extracfg.txt: no such file or directory
aoc_1  | 2021-02-04T04:37:34.983Z	INFO	service/service.go:411	Starting AWS OTel Collector...	{"Version": "v0.7.0", "GitHash": "14a0d2cf11fe4ed2cd254241acdda17c54a0e59e", "NumCPU": 12}
aoc_1  | 2021-02-04T04:37:34.984Z	INFO	service/service.go:255	Setting up own telemetry...
aoc_1  | 2021-02-04T04:37:34.984Z	INFO	service/telemetry.go:102	Serving Prometheus metrics	{"address": "localhost:8888", "level": 0, "service.instance.id": "f1c1104e-fe11-419e-b1c0-c502299c2694"}
aoc_1  | 2021-02-04T04:37:34.985Z	INFO	service/service.go:292	Loading configuration...
```

## Expected

- exit with 1
- print error out

```text
Pulling aoc (otel/opentelemetry-collector-dev:latest)...
latest: Pulling from otel/opentelemetry-collector-dev
9f67765df749: Pull complete
d253993c1c77: Pull complete
10422b86477b: Pull complete
Digest: sha256:bd89db598f5b4ff2a6d01b1c24984e2aa634f2480967a90648962681e8f596b7
Status: Downloaded newer image for otel/opentelemetry-collector-dev:latest
Recreating config-error_aoc_1 ... done
Attaching to config-error_aoc_1
aoc_1  | 2021-02-04T04:08:02.710Z	info	service/service.go:411	Starting OpenTelemetry Collector...	{"Version": "v0.19.0-14-g522fba3d", "GitHash": "522fba3d", "NumCPU": 12}
aoc_1  | 2021-02-04T04:08:02.710Z	info	service/service.go:255	Setting up own telemetry...
aoc_1  | 2021-02-04T04:08:02.711Z	info	service/telemetry.go:102	Serving Prometheus metrics	{"address": ":8888", "level": 0, "service.instance.id": "00b3b4f4-b7dc-44c1-83af-b7ee831d88a8"}
aoc_1  | 2021-02-04T04:08:02.711Z	info	service/service.go:292	Loading configuration...
aoc_1  | Error: cannot load configuration: error loading config file "/etc/otel-agent-config.yaml": While parsing config: yaml: line 10: did not find expected key
aoc_1  | 2021/02/04 04:08:02 application run finished with error: cannot load configuration: error loading config file "/etc/otel-agent-config.yaml": While parsing config: yaml: line 10: did not find expected key
config-error_aoc_1 exited with code 1
```

## Root Cause

Introduced in https://github.com/aws-observability/aws-otel-collector/pull/327/files#diff-512bdd2f9423476d0032108a24d5b265cebfb839ce7ab69831ed4c15c6778634
