### ISSUE TITLE
aws-otel-collector docker exits on custom config

### ISSUE THREAD

**Issue by kowshikn** [aws-observability/aws-otel-collector#350]
When I run a custom config, the aws-otel-collector docker image doesn't start up,

```
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting aws-ot-collector ... done
Attaching to aws-ot-collector
aws-ot-collector    | AWS OTel Collector version: v0.7.0
aws-ot-collector    | 2021/02/08 22:18:36 find no extra config, skip it, err: open /opt/aws/aws-otel-collector/etc/extracfg.txt: no such file or directory
aws-ot-collector    | 2021-02-08T22:18:36.067Z	INFO	service/service.go:411	Starting AWS OTel Collector...	{"Version": "v0.7.0", "GitHash": "14a0d2cf11fe4ed2cd254241acdda17c54a0e59e", "NumCPU": 16}
aws-ot-collector    | 2021-02-08T22:18:36.067Z	INFO	service/service.go:255	Setting up own telemetry...
aws-ot-collector    | 2021-02-08T22:18:36.069Z	INFO	service/telemetry.go:102	Serving Prometheus metrics	{"address": "localhost:8888", "level": 0, "service.instance.id": "53917e38-fef1-45ac-9f31-804972e3142e"}
aws-ot-collector    | 2021-02-08T22:18:36.069Z	INFO	service/service.go:292	Loading configuration...
aws-ot-collector exited with code 0

```

Below is my docker-compose file at locations: `/home/ec2-user/test/docker-compose.yml`

```
version: "3.7"
services:
  # AWS OTel Collector
  aws-ot-collector:
    container_name:  aws-ot-collector
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-agent-config.yaml 

```

Below is my config in file at location: `/home/ec2-user/test/otel-collector-config.yml`
```
receivers:
  jaeger:
    protocols:
      grpc:

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50


exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch/traces]
      exporters: [logging]
```

The same config works with opentelemetry-collector.
