### ISSUE TITLE
awsemf + eks: Authorization Error. Need guidance.

### ISSUE THREAD

**Issue by hossain-rayhan** [aws-observability/aws-otel-collector#367]
Hi EKS and awsemf exporter experts, I am having some issues while deploying the ADoT collector in an EKS EC2 cluster and using the awsemf expoerter. It throws the following error. 
`ERROR	awsemfexporter@v0.19.0/cwlog_client.go:117	cwlog_client: Error occurs in PutLogEvents	{"component_kind": "exporter", "component_type": "awsemf", "component_name": "awsemf", "error": "WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: 15859db3-8352-4885-a191-6c4cdd75d336"}`

I believe I have the right policy and I am not sure if I am missing anything. I am kind of new to Kubernetes world. Any guidance would be appreciated. 

My policy:
<img width="566" alt="Screen Shot 2021-02-17 at 1 01 19 PM" src="https://user-images.githubusercontent.com/5003238/108267602-437ba180-7120-11eb-9d4d-ff47d10ae429.png">

**Comment by mxiamxia** [comment]
How did you attach IAM policy? it should be attached to EC2 work nodes running in EKS cluster.

**Comment by hossain-rayhan** [comment]
```yaml
# create adot-col service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amp-iamproxy-ingest-service-account
  namespace: adot-col
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::803860917211:role/amp-iamproxy-ingest-role

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adotcol-admin-role
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/proxy
    - services
    - endpoints
    - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adotcol-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: amp-iamproxy-ingest-service-account
    namespace: adot-col
roleRef:
  kind: ClusterRole
  name: adotcol-admin-role
  apiGroup: rbac.authorization.k8s.io
  ```

**Comment by mxiamxia** [comment]
You also need to attach the role to your EC2 instances which is running the collector pods. 

https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/eks-demo.md#attach-eks-awsotel-iam-role-to-worker-nodes

**Comment by hossain-rayhan** [comment]
I updated the policy for EC2 instance role also. Still getting the same error. The error is something with assume role, I added that one also. Not sure what I am missing.

<img width="631" alt="Screen Shot 2021-02-17 at 1 38 41 PM" src="https://user-images.githubusercontent.com/5003238/108271474-b6d3e200-7125-11eb-8e7f-11e2c803294e.png">

**Comment by mxiamxia** [comment]
does your EC2 instance located in the same account with this role? `arn:aws:iam::803860917211:role/amp-iamproxy-ingest-role`. I think the problem is you need to allow your EKS IAM role assume your EC2 role. 

Another way, you dont' have to authenticate EKS with serviceaccount. you can just create a new EKS cluster, attach admin role to your eks ec2. then follow this instruction to setup ADOT.

**Comment by hossain-rayhan** [comment]
The default example is working fine and it can send logs to CloudWatch. However, when I am using prometheus receiver and adding extra permission using rbac, its not working. Trying to understand whats wrong with my configuration file.

**Comment by diclophis** [comment]
Cross check the endpoint url ... I think the docs have a typo it should be `https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-XXX/api/v1/remote_write`

**Comment by hossain-rayhan** [comment]
@diclophis I was using the `prometheus` receiver to collect data and `awsemf` exporter for sending to CloudWatch. I don't think I need to configure the remote_write. 
Here is the full config.

```yaml
---
# create adot-col namespace
apiVersion: v1
kind: Namespace
metadata:
  name: adot-col
  labels:
    name: adot-col

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-conf
  namespace: adot-col
  labels:
    app: aws-adot
    component: adot-collector-conf
data:
  adot-collector-config: |
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s

          scrape_configs:
          - job_name: 'kubernetes-service-endpoints'

            kubernetes_sd_configs:
            - role: endpoints

            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

            relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_scrape]
              action: keep
              regex: true

    exporters:
      awsemf:
        log_group_name: 'AOTLogGroup'
        log_stream_name: 'AOTLogStream'
        namespace: 'AOTMetricNS'
        dimension_rollup_option: 1
        region: us-east-2
      logging:
        loglevel: debug

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [logging, awsemf]
---
# create adot-col service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amp-iamproxy-ingest-service-account
  namespace: adot-col
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::803860917211:role/amp-iamproxy-ingest-role

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adotcol-admin-role
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/proxy
    - services
    - endpoints
    - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adotcol-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: amp-iamproxy-ingest-service-account
    namespace: adot-col
roleRef:
  kind: ClusterRole
  name: adotcol-admin-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: adot-collector
  namespace: adot-col
  labels:
    app: aws-adot
    component: adot-collector
spec:
  ports:
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: adot-collector
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adot-collector
  namespace: adot-col
  labels:
    app: aws-adot
    component: adot-collector
spec:
  selector:
    matchLabels:
      app: aws-adot
      component: adot-collector
  #minReadySeconds: 5
  serviceName: adot-collector
  template:
    metadata:
      labels:
        app: aws-adot
        component: adot-collector
    spec:
      serviceAccountName: amp-iamproxy-ingest-service-account
      containers:
      - command:
          - "/awscollector"
          - "--config=/conf/adot-collector-config.yaml"
        image: public.ecr.aws/aws-observability/aws-otel-collector:latest
        name: adot-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 8888  # Default endpoint for querying metrics.
        volumeMounts:
        - name: adot-collector-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: adot-collector-conf
            items:
              - key: adot-collector-config
                path: adot-collector-config.yaml
          name: adot-collector-config-vol
---
```
