### ISSUE TITLE
Exporting to multiple x-ray accounts

### ISSUE THREAD

**Issue by CathalAherne** [aws-observability/aws-otel-collector#384]
Hi,

Is it possible to export trace data to multiple x-ray accounts using the same collector. Considering the collector uses the aws credentials to decide which aws account to push data to, it seems it would be necessary to have more than one pair of credentials. Would this work, or would I just need to use 2 collectors and push the trace data to both?

**Comment by CathalAherne** [comment]
Found out how to do it. Just need to add this to the config file:
```
exporters:
  awsxray/1:
    region: 'eu-west-1'
  awsxray/2:
    region: 'eu-west-1'
    role_arn: cross account ARN

service:
  pipelines:
    traces/1:
      receivers: [otlp]
      exporters: [awsxray/1]
    traces/2:
      receivers: [ otlp ]
      exporters: [ awsxray/2 ]
```
