### ISSUE TITLE
Not recognizing AWS credentials either from env or ~/.aws/credentials

### ISSUE THREAD

**Issue by navsinha5** [aws-observability/aws-otel-collector#407]
Hi,

I am running the application in an EC2 instance (Ubuntu x86_64). The application fails to use the credentials provided via either env or shared credentials file. Whereas if I assign an IAM role to this instance it works fine. 

Usecase

> Prometheus -----> Collector -----> AWS Managed Prometheus

Application log

> application run finished with error: cannot setup pipelines: cannot build builtExporters: error creating awsprometheusremotewrite exporter: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Credentials

```
cat ~/.aws/credentials
[default]
aws_access_key_id = id
aws_secret_access_key = secret
```

Config

```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
          - targets: ['localhost:9090']

exporters:
  awsprometheusremotewrite:
    endpoint: "AMP_remote-write-uri"
    aws_auth:
      service: "aps"
      region: "eu-west-1"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [awsprometheusremotewrite]
```

What I am doing wrong here?
