### ISSUE TITLE
opentelemetry-collector between aws-otel-collector  Permanent error: SerializationException

### ISSUE THREAD

**Issue by SecretSun** [aws-observability/aws-otel-collector#537]
The aws-otel-collector erro:
2021-06-08T08:42:04.597Z error exporterhelper/queued_retry.go:243 Exporting failed. Try enabling retry_on_failure config option. {"kind": "exporter", "name": "awsxray", "error": "Permanent error: SerializationException: \n\tstatus code: 400, request id: bb92b15b-dea5-44c8-bd4a-68deeefd7735"}

Is there some bug between OpenTelemetry and X-Ray? 

Our process is as follows:
```
opentelemetry-collector (DaemonSet)
			|
opentelemetry-collector (Svc, Control sampling rate)
			|
aws-otel-collector (Svc, Send data to x-ray)
			|
		    aws x-ray
```

opentelemetry-collector (DaemonSet run) conf: 
```
  pipelines:
    traces:
      receivers: [otlp, opencensus, zipkin]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp]
```

opentelemetry-collector (Svc run, Control sampling rate) conf:
```
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      processors: [memory_limiter, resource, batch]
      exporters: [kafka, otlp]
```

aws-otel-collector (Svc run, Send data to x-ray) conf:
```
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [awsxray]
```
