### ISSUE TITLE
Allow metric type overrides for prometheus scrape

### ISSUE THREAD

**Issue by evmin** [aws-observability/aws-otel-collector#629]
**Is your feature request related to a problem? Please describe.**

At the moment a metric without explicit TYPE declaration is dropped by the prometheus scrape:

```
{2021-08-29 07:34:57.171703757 +0000 UTC m=+835.349148392, Level:info, Caller:go.opentelemetry.io/collector@v0.29.1-0.20210630003519-14d917479ef3/receiver/prometheusreceiver/internal/metrics_adjuster.go:302, Message:Adjust - skipping unexpected point, Stack:}
```

metric example:

```
ubuntu@ip-10-7-2-210:~/hserver$ curl localhost:8000/metrics
rts_gc_par_avg_bytes_int 5209386400
```

scrape configuration:

```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: node
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:8000']
```

**Describe the solution you'd like**
As a system admin I would like to be able to explicitly define prometheus TYPE override for the metric.

For example:

```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: node
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:8000']
          metric_type_override:
            - metric_name: rts_gc_par_avg_bytes_int
              type: gauge
```

**Describe alternatives you've considered**
At the moment I am considering a custom HTTP proxy that would add a type declaration for the metric
```
# TYPE rts_gc_par_avg_bytes_int gauge
```

Another possibly related issue: 
https://github.com/open-telemetry/opentelemetry-collector/issues/3118
