### ISSUE TITLE
Loading collector config from AOT_CONFIG_CONTENT causes ECS Task to Fail on v0.13.0

### ISSUE THREAD

**Issue by seng-siong** [aws-observability/aws-otel-collector#662]
- I am running AWS OTEL Collector as a sidecar in my ECS Task. 
- It is pulling config from an SSM Parameter.
- The config is as belows:
```yaml
receivers:
  awsecscontainermetrics:

exporters:
  otlp: 
    endpoint: <some reachable endpoint>
    insecure: true

processors:
  memory_limiter: 
    check_interval: 1s
    limit_mib: 512
  batch:
    timeout: 60s
    send_batch_size: 50
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.reserved
          - ecs.task.memory.utilized
          - ecs.task.cpu.reserved
          - ecs.task.cpu.utilized
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
          - container.duration

extensions:
  health_check:

service:
  extensions:
    - health_check
  pipelines:
    metrics:
      receivers: [awsecscontainermetrics]
      processors: [memory_limiter, batch, filter]
      exporters: [otlp]
```
- The config was working fine in v0.12.0 but was broken in v0.13.0 with the following error:

```
2021-09-23T12:55:06.340+08:00 | 2021/09/23 04:55:06 AWS OTel Collector version: v0.13.0
-- | --
  | 2021-09-23T12:55:06.345+08:00 | 2021/09/23 04:55:06 find no extra config, skip it, err: open /opt/aws/aws-otel-collector/etc/extracfg.txt: no such file or directory
  | 2021-09-23T12:55:06.345+08:00 | 2021/09/23 04:55:06 Reading AOT config from from environment: receivers:
  | 2021-09-23T12:55:06.345+08:00 | awsecscontainermetrics:
  | 2021-09-23T12:55:06.345+08:00 | exporters:
  | 2021-09-23T12:55:06.345+08:00 | otlp:
  | 2021-09-23T12:55:06.345+08:00 | endpoint: ****
  | 2021-09-23T12:55:06.345+08:00 | insecure: true
  | 2021-09-23T12:55:06.345+08:00 | processors:
  | 2021-09-23T12:55:06.345+08:00 | memory_limiter:
  | 2021-09-23T12:55:06.345+08:00 | check_interval: 1s
  | 2021-09-23T12:55:06.345+08:00 | limit_mib: 512
  | 2021-09-23T12:55:06.345+08:00 | batch:
  | 2021-09-23T12:55:06.345+08:00 | timeout: 60s
  | 2021-09-23T12:55:06.345+08:00 | send_batch_size: 50
  | 2021-09-23T12:55:06.345+08:00 | filter:
  | 2021-09-23T12:55:06.345+08:00 | metrics:
  | 2021-09-23T12:55:06.345+08:00 | include:
  | 2021-09-23T12:55:06.345+08:00 | match_type: strict
  | 2021-09-23T12:55:06.345+08:00 | metric_names:
  | 2021-09-23T12:55:06.345+08:00 | - ecs.task.memory.reserved
  | 2021-09-23T12:55:06.345+08:00 | - ecs.task.memory.utilized
  | 2021-09-23T12:55:06.345+08:00 | - ecs.task.cpu.reserved
  | 2021-09-23T12:55:06.345+08:00 | - ecs.task.cpu.utilized
  | 2021-09-23T12:55:06.345+08:00 | - ecs.task.network.rate.rx
  | 2021-09-23T12:55:06.345+08:00 | - ecs.task.network.rate.tx
  | 2021-09-23T12:55:06.345+08:00 | - ecs.task.storage.read_bytes
  | 2021-09-23T12:55:06.345+08:00 | - ecs.task.storage.write_bytes
  | 2021-09-23T12:55:06.345+08:00 | - container.duration
  | 2021-09-23T12:55:06.345+08:00 | extensions:
  | 2021-09-23T12:55:06.345+08:00 | health_check:
  | 2021-09-23T12:55:06.345+08:00 | service:
  | 2021-09-23T12:55:06.345+08:00 | extensions:
  | 2021-09-23T12:55:06.345+08:00 | - health_check
  | 2021-09-23T12:55:06.345+08:00 | pipelines:
  | 2021-09-23T12:55:06.345+08:00 | metrics:
  | 2021-09-23T12:55:06.345+08:00 | receivers: [awsecscontainermetrics]
  | 2021-09-23T12:55:06.345+08:00 | processors: [memory_limiter, batch, filter]
  | 2021-09-23T12:55:06.345+08:00 | exporters: [otlp]
  | 2021-09-23T12:55:06.359+08:00 | Error: cannot load configuration: error reading exporters configuration for otlp: 1 error(s) decoding:
  | 2021-09-23T12:55:06.359+08:00 | * '' has invalid keys: insecure
  | 2021-09-23T12:55:06.359+08:00 | 2021/09/23 04:55:06 application run finished with error: cannot load configuration: error reading exporters configuration for otlp: 1 error(s) decoding:
  | 2021-09-23T12:55:06.359+08:00 | * '' has invalid keys: insecure

```

**Comment by seng-siong** [comment]
looks like there was a change to the configuration parameters for otlp exporters:

```yaml

# Old
exporters:
  otlp:
    endpoint: some.example.com
    insecure: true

# New
exporters:
  otlp:
    endpoint: some.example.com
    tls:
      insecure: true
```
