### ISSUE TITLE
Role_arn not getting used with awsprometheusremotewrite exporter

### ISSUE THREAD

**Issue by redhotchili** [aws-observability/aws-otel-collector#670]
Hi,

so I'm running adot collector on ECS and got the config set up like this:

```
exporters:
  awsprometheusremotewrite:
    endpoint: <...>/api/v1/remote_write
    aws_auth:
      region: eu-west-1
      service: aps
      role_arn: <role for writing to managed prometheus>
```
      
But in the logs getting export failure:

```
{
    "kind": "exporter",
    "name": "awsprometheusremotewrite",
    "error": "Permanent error: Post \"https://<endpoint>\": RequestCanceled: request context canceled\ncaused by: context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
    "dropped_items": 5
}
```

When I check cloudtrail or role access log, it's not been accessed/assumed and doesn't look like the service is even trying to assume it.

Is the role_arn field supposed to work in this case? I'd like to use it for cross account access in the future, so directly attaching access policy to ecs role is not an option.
