### ISSUE TITLE
Using awsecscontainermetrics receiver with awsprometheusremotewrite doesn't include any labels

### ISSUE THREAD

**Issue by bohlander** [aws-observability/aws-otel-collector#706]
**Describe the bug**
I have the following setup:

```
service:
  pipelines:
    metrics/perfprom:
      receivers: [awsecscontainermetrics]
      exporters: [awsprometheusremotewrite]
```

I see metrics being reported inside of prometheus, but they don't have any labels. I think this might be because prometheus only accepts labels that do not include '.'.  So I tried the following approach to rename a single label:

```
 metricstransform/prom:
    transforms:
      - include: ^ecs\.
        match_type: regexp
        action: update
        operations:
          - action: update_label
            label: aws.ecs.task.family
            new_label: aws_ecs_task_family

service:
  pipelines:
    metrics/perfprom:
      receivers: [awsecscontainermetrics]
      processors: [metricstransform/prom]
      exporters: [awsprometheusremotewrite]
```

The label data still isn't getting passed through to prometheus correctly.  Are resource attributes not included in metrics when output from awsecscontainermetrics?  I assumed they were given how samples like https://aws-otel.github.io/docs/components/ecs-metrics-receiver#full-configuration-for-task--and-container-level-metrics work.  

If i'm doing this wrong, can you suggest a way to include these task and container metrics in a way that Prometheus will accept them?

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**Environment**
Describe any aspect of your environment relevant to the problem.

**Additional context**

**Comment by chenfeilee** [comment]
@bohlander a fellow aws-otel-collector user here too and maybe you can try adding `exporters.awsprometheusremotewrite.resource_to_telemetry_conversion.enabled: true` to see whether it helps :) Inspiration from https://github.com/aws-observability/aws-otel-collector/issues/472 

e.g. 
```
exporters:
  awsprometheusremotewrite:
    endpoint: ${PROM_REMOTE_WRITE_ENDPOINT}
    resource_to_telemetry_conversion:
      enabled: true
```
