### ISSUE TITLE
Labels from env is not being expanded in config

### ISSUE THREAD

**Issue by antonzhyliuk** [aws-observability/aws-otel-collector#748]
**Describe the bug**
config for prometheus containing env vars which is not being expanded.
```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 1m
        scrape_timeout: 10s

      scrape_configs:
        - job_name: jmx
          static_configs:
            - targets: ["service:8080"]
              labels:
                service: toaster
                runtime_environment: "${RUNTIME_ENVIRONMENT}"
                deployment: "${DEPLOYMENT}"
```

when I read metrics from prometheus I could find metrics with label runtime_environment being set as plain string `"${RUNTIME_ENVIRONMENT}"`

**What did you expect to see?**
I expect to see value of env var being set to the label

**Environment**
I see the problem in the latest version: 0.14.0

**Additional context**
I think it worked well on the previous versions. I'll try to find which one is working
