### ISSUE TITLE
Environment variables are not getting resolved when passing config through SSM 

### ISSUE THREAD

**Issue by anilgvpcoe** [aws-observability/aws-otel-collector#808]
**Describe the question**
We are using aws distro sidecar for our ECS tasks. Based on [config-through-ssm](https://aws-otel.github.io/docs/setup/ecs/config-through-ssm) we configured a secret and are passing the config to AWS distro, this works fine when config has actual values as below

```
receivers:
    otlp:
      protocols:
          grpc:
          http:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'local-spring-boot-actuator'
            metrics_path: '/<service-name>/mgmt/prometheus'
```

 
However in our case we want to use env variables instead of hardcoding values in [config](https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables). So we updated config to

```
receivers:
    otlp:
      protocols:
          grpc:
          http:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'local-spring-boot-actuator'
            metrics_path: '/${SERVICE_NAME}/mgmt/prometheus'
```

and added SERVICE_NAME env variable in container.  Now when aws-distro starts it is unable to reach the same destination we keep getting connect exception in logs.

Is this expected and are there sample configs we can refer to for using env variables in config file

**Steps to reproduce if your question is related to an action**
Add some env variables in ECS task container. Use the env variables in a config file and load the config file through SSM or secret. Check if env variables are resolving to actual values at runtime.

**What did you expect to see?**
ENV variables should be resolved to actual values as mentioned [here](https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables)

**Environment**

- ECS task with aws-distro as a sidecar container
- Config is being loaded via AOT_CONFIG_CONTENT pointing to a secret

**Additional context**
Please let me know if you need more info
