### ISSUE TITLE
403 UnrecognizedClientException Python Tracing

### ISSUE THREAD

**Issue by zqumei0** [aws-observability/aws-otel-collector#814]
**Describe the bug**
I am sending a trace from a FastAPI endpoint that returns environment information to the client. The trace is sent to the aws-otel-collector docker container, but the container outputs an exporter 403 UnrecognizedClientException error.

**Steps to reproduce**
HTTP protocol used to send traces to otel collector, not GRPC.
Config file being used:
```
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55681

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 5
  batch/metrics:
    timeout: 60s

exporters:
  awsxray:
    region: "us-east-1"
    index_all_attributes: true
  awsemf:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awsemf]

  extensions: [health_check]
```

**What did you expect to see?**
I was expecting to see traces tracked from the application in the AWS X-Ray console.

**What did you see instead?**
AWS otel collector outputs an error from aws xray exporter:
```
web_app_1 | 2021-12-16 18:53:18 DEBUG    http://169.254.170.6:55681 "POST /v1/traces HTTP/1.1" 200 0
aws-otel-collector_1   | 2021-12-16T18:53:19.325Z       error   exporterhelper/queued_retry.go:149      Exporting failed. Try enabling retry_on_failure config option.  {"kind": "exporter", "name": "awsxray", "error": "Permanent error: UnrecognizedClientException: \n\tstatus code: 403, request id: 781a9f3c-f13d-4326-a4c7-11f6dc2b2c96"}
aws-otel-collector_1   | go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/exporter/exporterhelper/queued_retry.go:149
aws-otel-collector_1   | go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/exporter/exporterhelper/traces.go:136
aws-otel-collector_1   | go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/exporter/exporterhelper/queued_retry.go:83
aws-otel-collector_1   | go.opentelemetry.io/collector/exporter/exporterhelper.NewTracesExporter.func2
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/exporter/exporterhelper/traces.go:115
aws-otel-collector_1   | go.opentelemetry.io/collector/consumer/consumerhelper.ConsumeTracesFunc.ConsumeTraces
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/consumer/consumerhelper/traces.go:29
aws-otel-collector_1   | go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).export
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/processor/batchprocessor/batch_processor.go:256
aws-otel-collector_1   | go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/processor/batchprocessor/batch_processor.go:184
aws-otel-collector_1   | go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/processor/batchprocessor/batch_processor.go:145
aws-otel-collector_1   | 2021-12-16T18:53:19.326Z       error   exporterhelper/queued_retry.go:85       Exporting failed. Dropping data. Try enabling sending_queue to survive temporary failures.      {"kind": "exporter", "name": "awsxray", "dropped_items": 3}
aws-otel-collector_1   | go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/exporter/exporterhelper/queued_retry.go:85
aws-otel-collector_1   | go.opentelemetry.io/collector/exporter/exporterhelper.NewTracesExporter.func2
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/exporter/exporterhelper/traces.go:115
aws-otel-collector_1   | go.opentelemetry.io/collector/consumer/consumerhelper.ConsumeTracesFunc.ConsumeTraces
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/consumer/consumerhelper/traces.go:29
aws-otel-collector_1   | go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).export
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/processor/batchprocessor/batch_processor.go:256
aws-otel-collector_1   | go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/processor/batchprocessor/batch_processor.go:184
aws-otel-collector_1   | go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle
aws-otel-collector_1   |        go.opentelemetry.io/collector@v0.39.0/processor/batchprocessor/batch_processor.go:145
aws-otel-collector_1   | 2021-12-16T18:53:19.326Z       warn    batchprocessor/batch_processor.go:185   Sender failed   {"kind": "processor", "name": "batch/traces", "error": "Permanent error: UnrecognizedClientException: \n\tstatus code: 403, request id: 781a9f3c-f13d-4326-a4c7-11f6dc2b2c96"}
```

**Environment**
Currently hosting a FastAPI web application and ADOT collector container via docker-compose.
