### ISSUE TITLE
How to get full PodName from EKS in EMF metrics?

### ISSUE THREAD

**Issue by jbeemster** [aws-observability/aws-otel-collector#852]
**Describe the question**
I want the full PodName to be used in metrics exported to CloudWatch.  Currently it seems that the PodName attribute used in the `metric_declarations` is coming through without any of the random entropy on the end - this means that I am unable to clearly see what the usage of an individual Pod is currently - just the group of Pods aggregated as a whole.

I can see in the `performance` logs that the `kubernetes.pod_name` does have the correct value but the top level `PodName` is missing the suffix which adds entropy to the name.

Ideally I would like to be able to export both metrics at this higher level - essentially at the deployment level for general alarming - but would also like to be able to export metrics specific to an individual pod to aid in debugging problems.

---

Reading through the docs I have tried using `K8sPodName` as a dimension but does not seem to fire at all.

**What did you expect to see?**
A set of metrics specific to an individual pod in my EKS cluster.

**Environment**
EKS v1.19, OTel Collector v0.15.1

**Additional context**
Configuration file is as follow - `K8sPodName` does not seem to do anything currently.

```
    extensions:
      health_check:

    receivers:
      awscontainerinsightreceiver:

    processors:
      batch/metrics:
        timeout: 60s

    exporters:
      awsemf:
        namespace: ContainerInsights
        log_group_name: '/aws/containerinsights/{ClusterName}/performance'
        log_stream_name: '{NodeName}'
        resource_to_telemetry_conversion:
          enabled: true
        dimension_rollup_option: NoDimensionRollup
        parse_json_encoded_attr_values: [Sources, kubernetes]
        metric_declarations:
          - dimensions: [[PodName, Namespace, ClusterName]]
            metric_name_selectors:
              - pod_cpu_utilization
              - pod_memory_utilization
              - pod_number_of_running_containers
          - dimensions: [[K8sPodName, Namespace, ClusterName]]
            metric_name_selectors:
              - pod_cpu_utilization
              - pod_memory_utilization

    service:
      pipelines:
        metrics:
          receivers: [awscontainerinsightreceiver]
          processors: [batch/metrics]
          exporters: [awsemf]

      extensions: [health_check]
```

**Comment by sethAmazon** [comment]
Can you post the docs you were reading? Looking through the code I think the dimension you have is related to this log line https://github.com/open-telemetry/opentelemetry-collector/blob/main/model/semconv/v1.5.0/resource.go#L502 thus this not working make sense to me.

**Comment by sethAmazon** [comment]
Can you also post the logs please.

**Comment by sethAmazon** [comment]
There is a config for prefer_full_pod_name maybe you can give that shot.

**Comment by jbeemster** [comment]
Hey @sethAmazon I have tried that setting as well but to no avail.  From that description if it can be set from the relevant controller it is so that setting never comes into play from what I can tell - though that is just a hunch!

If there is no way to reliably create a metric using the full pod name currently that's OK - but would then be great to understand if that kind of change would be going into the roadmap?

**Comment by sethAmazon** [comment]
Can you please post your metadata.ownerReferences for your pod

**Comment by jbeemster** [comment]
Hey @sethAmazon for one of my pods in EKS for CNI:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-01-03T13:05:50Z"
  generateName: aws-node-
  labels:
    app.kubernetes.io/name: aws-node
    controller-revision-hash: 5b558d4b79
    k8s-app: aws-node
    pod-template-generation: "1"
  name: aws-node-mbtzd
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: aws-node
    uid: 28fa15f5-4d98-495f-9dec-5a54c681e9f7
```
