### ISSUE TITLE
EKS fargate otel awsxray exporter fail 

### ISSUE THREAD

**Issue by akshayvadher** [aws-observability/aws-otel-collector#928]
**Describe the bug**
EKS fargate only (no nodes) otel awsxray exporter fail 

**Steps to reproduce**
Create EKS fargate cluster (no nodes, everything runs on fargate)

Create a spring boot jar application. Add following steps in Dockerfile
```
ADD https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar /opt/aws-opentelemetry-agent.jar
ENV JAVA_TOOL_OPTIONS=-javaagent:/opt/aws-opentelemetry-agent.jar
```

Provide following IAM permission to `pod execution role` (fargate role) and clusture role (I know this role might not need permission)
```
{
    "Statement": [
        {
            "Action": [
                "logs:PutLogEvents",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DescribeLogStreams",
                "logs:DescribeLogGroups",
                "xray:PutTraceSegments",
                "xray:PutTelemetryRecords",
                "xray:GetSamplingRules",
                "xray:GetSamplingTargets",
                "xray:GetSamplingStatisticSummaries",
                "ssm:GetParameters"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ],
    "Version": "2012-10-17"
}
```

Inside kubernetes deployment, add aws-otel-collector sidecar as following
```
    spec:
      containers:
        - image: image:${BUILD_ID}
          name: api
          env:
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.namespace=AWSObservability,service.name=CloudWatchEKSService
          - name: OTEL_RESOURCE
            value: main-dev
        - name: aws-otel-collector
          image: amazon/aws-otel-collector:latest
          volumeMounts:
            - mountPath: /etc/otel-config.yaml
              subPath: otel-config.yaml
              name: telemetry-config
          env:
            - name: AWS_REGION
              value: "ap-southeast-1"
      volumes:
        - name: telemetry-config
          configMap:
            name: telemetry-config
```

Create a config map for telemetry-config
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
  namespace: app
data:
  otel-config.yaml: |
    extensions:
      health_check:
    
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:55681
      awsxray:
        endpoint: 0.0.0.0:2000
        transport: udp
    
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
      batch/metrics:
        timeout: 60s
    
    exporters:
      logging:
        loglevel: debug
      awsxray:
        region: "ap-southeast-2"
        role_arn: "arn:aws:iam::ACCOUNT_ID:role/main-dev-fargate_cluster_role"
      awsemf:
        region: "ap-southeast-2"
        role_arn: "arn:aws:iam::ACCOUNT_ID:role/main-dev-fargate_cluster_role"
    
    service:
      pipelines:
        traces:
          receivers: [otlp,awsxray]
          processors: [batch/traces]
          exporters: [awsxray]
        metrics:
          receivers: [otlp]
          processors: [batch/metrics]
          exporters: [awsemf]
    
      extensions: [health_check]
      

```

**What did you expect to see?**
When app starts, it should collect traces and export to AWS X-Ray

**What did you see instead?**
Following error
```
2022-01-27T18:54:00.961Z        warn    batchprocessor/batch_processor.go:185   Sender failed   {"kind": "processor", "name": "batch/traces", "error": "NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
2022-01-27T18:54:11.102Z        error   exporterhelper/queued_retry.go:149      Exporting failed. Try enabling retry_on_failure config option.  {"kind": "exporter", "name": "awsxray", "error": "NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
```

**Additional context**
I am assuming no extra auth steps are required as, as per [this](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/eks-demo.md) official example, if the IAM role has the permission, it should work

**Comment by anuraaga** [comment]
Hi @akshayvadher - FWIU, pod execution roles on fargate are only for giving permissions for the actual k8s infrastructure logic run by a pod, for example, pulling the container image that will be run. But that role isn't actually used by the process running within the pod after everything is set up. This differs from EC2, which the demo uses, where the node's IAM role is used by apps themselves.

There are many different patterns for providing authentication to a pod running in EKS, but I would usually recommend associating a role (not the pod execution role but a different one for the app) with a service account mounted to the pod if you can

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by sethAmazon** [comment]
I agree with @anuraaga. We set this up in our test fw using oidc assume role.

**Comment by akshayvadher** [comment]
@sethAmazon @anuraaga Thanks for the response. 
Can you please help me by pointing at example configuration etc? I am not able to find one for EKS. 

Following is my Trust relationships. `app` is the namespace and `otel` is service account name
![image](https://user-images.githubusercontent.com/2619644/151678758-4e2deb26-c9fc-4456-95da-3e555a3b07ce.png)

And following is the configuration I tried
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
  namespace: app
data:
  otel-config.yaml: |
    extensions:
    #  health_check:
      oidc:
        issuer_url: oidc.eks.ap-southeast-1.amazonaws.com/id/OIDC_ID
        audience: collector
    
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:55681
      awsxray:
        endpoint: 0.0.0.0:2000
        transport: udp
    
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
      batch/metrics:
        timeout: 60s
    
    exporters:
      logging:
        loglevel: debug
      awsxray:
        region: "ap-southeast-2"
        role_arn: "arn:aws:iam::ACCOUNT_ID:role/main-dev-otel"
        auth:
          authenticator: oidc
    #  awsemf:
    #    region: "ap-southeast-2"
    #    role_arn: "arn:aws:iam::ACCOUNT_ID:role/main-dev-otel"
    
    service:
      pipelines:
        traces:
          receivers: [otlp,awsxray]
          processors: [batch/traces]
          exporters: [awsxray]
        metrics:
          receivers: [otlp]
          processors: [batch/metrics]
          exporters: [awsemf]
    
      # extensions: [health_check]
      extensions: [oidc]
      
```

Appologies If this sounds trivial.
