### ISSUE TITLE
Running layer inside container crashes on execution

### ISSUE THREAD

**Issue by brett-bim** [aws-observability/aws-otel-collector#932]
**Describe the question**
I have a Python lambda that is deployed as a container.  I'm trying to run the otel collector as a layer inside that container.  I have it copied to the container with what I think are the appropriate ENV variables and configuration but when I execute the function, I get the following error.  

2022/01/27 23:41:13 AWS OTel Collector version: v0.15.1
2022/01/27 23:41:13 find no extra config, skip it, err: open /opt/aws/aws-otel-collector/etc/extracfg.txt: no such file or directory
2022/01/27 23:41:13 D! fail to chmod on log file due to : mkdir /opt/aws: read-only file system 

**Environment**
Dockerfile
```
FROM public.ecr.aws/aws-observability/aws-otel-collector:latest as extensions-layer
WORKDIR /opt/extensions

FROM public.ecr.aws/lambda/python:3.8

ENV NLTK_DATA=${LAMBDA_TASK_ROOT}/data
ENV PYTHONPATH=${PYTHONPATH}:${LAMBDA_TASK_ROOT}


RUN mkdir -p ${LAMBDA_TASK_ROOT}
WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements/prod.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip3 install -r ${LAMBDA_TASK_ROOT}/requirements.txt
RUN python3 -m nltk.downloader -d ${LAMBDA_TASK_ROOT}/data stopwords

COPY beacon/ ${LAMBDA_TASK_ROOT}/beacon
COPY stopwords.txt ${LAMBDA_TASK_ROOT}
COPY fault_keywords.txt ${LAMBDA_TASK_ROOT}
COPY otelcollector.yaml ${LAMBDA_TASK_ROOT}

COPY --from=extensions-layer . /opt/extensions/ 
RUN chmod +x /opt/extensions/awscollector

CMD [ "beacon.aws.lambda_handler" ]
```

OTel collector config file:
```
#collector.yaml in the root directory
#Set an environemnt variable 'OPENTELEMETRY_COLLECTOR_CONFIG_FILE' to '/var/task/collector.yaml'

receivers:
  otlp:
    protocols:
      grpc:
      http:

# Honeycomb Collector configuration
exporters:
  otlp:
    endpoint: api.honeycomb.io:443
    headers:
      # You can find your Honeycomb authentication token at https://ui.honeycomb.io/account
      - "x-honeycomb-team" : "myapikey"
      # You can use any string for your dataset name, it will be created if it doesn't exist.
      - "x-honeycomb-dataset" : "some_dataset"

#enables output for traces to xray
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
```

ENV Variables:
```
OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/otelcollector.yaml
AWS_LAMBDA_EXEC_WRAPPER: /opt/extensions/awscollector
```

Any information as to what the error message means would be appreciateed
