### ISSUE TITLE
aws.ecs.service.name undefined

### ISSUE THREAD

**Issue by chenfeilee** [aws-observability/aws-otel-collector#939]
**Describe the question**
We have deployed aws-otel-collector as sidecar container in ECS and have configured `awsecscontainermetrics`. We are sending the metrics collected to AMP via `awsprometheusremotewrite`.

We can see all the resource attributes and metrics labels showing up just fine except `aws.ecs.service.name` which is showing up as "undefined". Just wondering if this is the expected behavior?

**Steps to reproduce if your question is related to an action**
1. Deploy aws-otel-collector as sidecar container in ECS
2. Define receiver as `awsecscontainermetrics` and exporter as `awsprometheusremotewrite`

**What did you expect to see?**
`aws.ecs.service.name` to display the correct value

**Environment**
ECS

**Additional context**
Config used for aws-otel-collector:
```
receivers:
  awsecscontainermetrics:
    collection_interval: 15s
processors:
  filter:
    metrics:
      include:
        match_type: regexp
        metric_names:
        - .*memory.reserved
        - .*memory.utilized
        - .*cpu.reserved
        - .*cpu.utilized
        - .*network.rate.rx
        - .*network.rate.tx
        - .*storage.read_bytes
        - .*storage.write_bytes
  resource:
    attributes:
    - key: aws.ecs.task.id
      action: delete
    - key: aws.ecs.task.pull_started_at
      action: delete 
    - key: aws.ecs.task.pull_stopped_at
      action: delete 
    - key: aws.ecs.task.arn
      action: delete 
    - key: aws.ecs.container.image.id
      action: delete 
    - key: aws.ecs.container.created_at
      action: delete 
    - key: aws.ecs.container.finished_at
      action: delete 
    - key: container.id
      action: delete 
    - key: aws.ecs.container.exit_code
      action: delete 
    - key: opencensus.resourcetype
      action: delete 
exporters:
  awsprometheusremotewrite:
    endpoint: ${PROM_REMOTE_WRITE_ENDPOINT}
    resource_to_telemetry_conversion:
      enabled: true
    aws_auth:
      region: ${PROM_REMOTE_WRITE_ENDPOINT_REGION}
      role_arn: ${PROM_REMOTE_WRITE_IAM_ROLE}
  logging:
    loglevel: warn
service:
  pipelines:
    metrics/ecs:
      receivers: [awsecscontainermetrics]
      processors: [filter, resource]
      exporters: [logging, awsprometheusremotewrite]
```
