### ISSUE TITLE
awsprometheusremotewriteexporter drop  all labels except instance

### ISSUE THREAD

**Issue by h-nago** [aws-observability/aws-otel-collector#958]
I want to send ecs metrics to AMP.
But awsprometheusremotewriteexporter drop  all labels except instance.

configuration file looks like the following.
```yaml
receivers:
  awsecscontainermetrics:
processors:
  resource:
    attributes:
      - key: taskid
        from_attribute: aws.ecs.task.id
        action: insert
      - key: instance
        from_attribute: aws.ecs.task.id
        action: insert
exporters:
  awsprometheusremotewrite:
    endpoint: https://aps-workspaces.region.amazonaws.com/workspaces/ws-xxx/api/v1/remote_write
  logging:
    logLevel: debug
service:
  pipelines:
    metrics:   
      receivers: [awsecscontainermetrics]
      processors: [resource]
      exporters: [awsprometheusremotewrite,logging]
```

With this setting, I get a graph below.
<img width="1367" alt="スクリーンショット 2022-02-02 16 48 34" src="https://user-images.githubusercontent.com/30610744/152113911-824c64fe-c12e-4edd-b8b0-0f0a6ea68203.png">

I expect to get metics like the following. But The taskid label has been dropped.
```
container_memory_usage{instance="04d415c45c274966b5f9c164d2d705f6", taskid="04d415c45c274966b5f9c164d2d705f6"}
```

**Comment by jefchien** [comment]
It looks like the PRW exporter drops all resource attributes except for `instance` and `job` (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheusremotewrite/helper.go#L207). This unfortunately causes it to ignore the `taskid` attached by the `resourceprocessor`.

**Comment by chenfeilee** [comment]
@h-nago a fellow aws-otel-collector user here too and you can try adding exporters.awsprometheusremotewrite.resource_to_telemetry_conversion.enabled: true to see whether it helps. Inspiration from https://github.com/aws-observability/aws-otel-collector/issues/472

e.g.

```
exporters:
  awsprometheusremotewrite:
    endpoint: ${PROM_REMOTE_WRITE_ENDPOINT}
    resource_to_telemetry_conversion:
      enabled: true
```
