### ISSUE TITLE
Unable to Filter Metrics Using Resource Attributes - resource_attributes

### ISSUE THREAD

**Issue by mskhan-devops** [aws-observability/aws-otel-collector#987]
Hi Everyone,
As per the example on page opentelemetry-collector-contrib/processor/filterprocessor, I am trying to configure ADOT Collector Pipeline for EKS cluster to publish metrics to CloudWatch Container Insights:

```
processors:
  filter/1:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - pod_cpu_.*
```
This works fine and I see filtered metrics against my apps in the Container Insights.

The problem is as soon as I add `resource_attributes` to the above configuration to filter out metrics against the specific app running in the EKS cluster, like below:

```
processors:
  filter/1:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - pod_cpu_.*
        resource_attributes:
          - Key: k8s.pod.name
            Value: myapp-pod-with-hash.*
```

**AWS ADOT Collector stops publishing any metrics to Container Insights. Can anyone please help with this?**

I am using this guide and sample config file:
[Cost savings by customizing metrics sent by Container Insights in Amazon EKS](https://aws.amazon.com/blogs/containers/cost-savings-by-customizing-metrics-sent-by-container-insights-in-amazon-eks/)

Sample config file:
[otel-container-insights-infra.yaml](https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/deployment-template/eks/otel-container-insights-infra.yaml)

Thanks

**Comment by tomiszili** [comment]
I have the same problem but with k8s namespace. @mskhan-devops how did you solve your problem?

**Comment by mskhan-devops** [comment]
> 

Hi @tomiszili ,

Could you please explain how you intend to use the filter processor? Do you want metrics for PODs in a particular namespace filtered?

Could you please share your config file so I can see what you're filtering on.

**Comment by tomiszili** [comment]
hello @mskhan-devops 

here is my non working manifest
```
---
    # create cwagent service account and role binding
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: aws-otel-sa
      namespace: kube-system

    ---
    kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: aoc-agent-role
    rules:
      - apiGroups: [""]
        resources: ["pods", "nodes", "endpoints"]
        verbs: ["list", "watch", "get"]
      - apiGroups: ["apps"]
        resources: ["replicasets"]
        verbs: ["list", "watch", "get"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["list", "watch"]
      - apiGroups: [""]
        resources: ["nodes/proxy"]
        verbs: ["get"]
      - apiGroups: [""]
        resources: ["nodes/stats", "configmaps", "events"]
        verbs: ["create", "get"]
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["update"]
      - apiGroups: [""]
        resources: ["configmaps"]
        resourceNames: ["otel-container-insight-clusterleader"]
        verbs: ["get", "update", "create"]
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["create", "get", "update"]
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        resourceNames: ["otel-container-insight-clusterleader"]
        verbs: ["get", "update", "create"]

    ---
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: aoc-agent-role-binding
    subjects:
      - kind: ServiceAccount
        name: aws-otel-sa
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: aoc-agent-role
      apiGroup: rbac.authorization.k8s.io

    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: otel-agent-conf
      namespace: kube-system
      labels:
        app: opentelemetry
        component: otel-agent-conf
    data:
      otel-agent-config: |
        extensions:
          health_check:

        receivers:
          awscontainerinsightreceiver:
            # all parameters are optional
            collection_interval: 60s
            container_orchestrator: eks
            add_service_as_attribute: false
            prefer_full_pod_name: true
            add_full_pod_name_metric_label: true

        processors:
          batch/metrics:
            timeout: 60s

          filter1:
          # any names NOT matching filters are excluded from remainder of pipeline
            metrics:
              include:
                match_type: regexp
                resource_attributes:
                  - Key: metadata.namespace
                    Value: ^perftest$

        exporters:
          awsemf:
            namespace: ContainerInsights
            log_group_name: '/aws/containerinsights/{ClusterName}/performance'
            log_stream_name: '{NodeName}'
            resource_to_telemetry_conversion:
              enabled: true
            dimension_rollup_option: NoDimensionRollup
            parse_json_encoded_attr_values: [Sources, kubernetes]
            metric_declarations:

              # pod metrics
              - dimensions: [[PodName, Namespace, ClusterName]]
                metric_name_selectors:
                  - pod_cpu_utilization
                  - pod_memory_utilization
                # label_matchers:
                #   - label_names:
                #       - Namespace
                #     regex: "^perftest*"

        service:
          telemetry:
            logs:
              level: "debug"
          pipelines:
            metrics:
              receivers: [awscontainerinsightreceiver]
              processors: [batch/metrics]
              exporters: [awsemf]

          extensions: [health_check]

    ---
    # create Daemonset
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: aws-otel-eks-ci
      namespace: kube-system
    spec:
      selector:
        matchLabels:
          name: aws-otel-eks-ci
      template:
        metadata:
          labels:
            name: aws-otel-eks-ci
        spec:
          containers:
            - name: aws-otel-collector
              image: amazon/aws-otel-collector:v0.18.0
              env:
                - name: K8S_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: HOST_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: K8S_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              imagePullPolicy: Always
              command:
                - "/awscollector"
                - "--config=/conf/otel-agent-config.yaml"
              volumeMounts:
                - name: rootfs
                  mountPath: /rootfs
                  readOnly: true
                - name: dockersock
                  mountPath: /var/run/docker.sock
                  readOnly: true
                - name: varlibdocker
                  mountPath: /var/lib/docker
                  readOnly: true
                - name: sys
                  mountPath: /sys
                  readOnly: true
                - name: devdisk
                  mountPath: /dev/disk
                  readOnly: true
                - name: otel-agent-config-vol
                  mountPath: /conf
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 200m
                  memory: 200Mi
          volumes:
            - configMap:
                name: otel-agent-conf
                items:
                  - key: otel-agent-config
                    path: otel-agent-config.yaml
              name: otel-agent-config-vol
            - name: rootfs
              hostPath:
                path: /
            - name: dockersock
              hostPath:
                path: /var/run/docker.sock
            - name: varlibdocker
              hostPath:
                path: /var/lib/docker
            - name: sys
              hostPath:
                path: /sys
            - name: devdisk
              hostPath:
                path: /dev/disk/
          serviceAccountName: aws-otel-sa
```
i can only filter to specific namespace with the `label_matchers` in the awsemf section.

I have tried to filter only the cpu and memory utilization but those are not working either. So i guess the whole filtering procedure has some issues or lack of documentation.

**Comment by mskhan-devops** [comment]
Hello @tomiszili ,
Sorry for the late response.

It appears you are using `resource_attributes` with a key `metadata.namespace` that is not in the "Resource labels" in Kubernetes (EKS).

Would it be possible for you to try the following and see if it works.

```
          filter1:
          # any names NOT matching filters are excluded from remainder of pipeline
            metrics:
              include:
                match_type: regexp
                resource_attributes:
                  - Key: Namespace
                    Value: ^perftest$

```
