### ISSUE TITLE
Ability to set log retention on CloudWatch log group when using awsemf exporter

### ISSUE THREAD

**Issue by tmokmss** [aws-observability/aws-otel-collector#991]
**Is your feature request related to a problem? Please describe.**
When using awsemf exporter, aws-otel automatically creates CloudWatch Log group. The resulting log group doesn't have log retention set. Sometimes it contradicts our security policy.

**Describe the solution you'd like**
Create a field like `log_retention` on [aws emf config section](https://aws-otel.github.io/docs/getting-started/cloudwatch-metrics#cloudwatch-emf-exporter-awsemf).

**Describe alternatives you've considered**
Currently to set log retention, we need to create log group by ourselves before aws-otel starts.

**Additional context**
n/a

**Comment by lorelei-rupp-imprivata** [comment]
any updates on this? we would love to not have "never expire" set on this log group

**Comment by bryan-aguilar** [comment]
Hi @lorelei-rupp-imprivata,

No updates, but I have reopened this request and will bring it up with the team.

**Comment by humivo** [comment]
Hey everyone, I just made changes upstream to add log retention and so this feature will be included in our next upcoming collector release.  Thank you and please look out for it!

**Comment by lorelei-rupp-imprivata** [comment]
@humivo do you know what version specifically it will be in, so I can make sure we upgrade to it?

**Comment by bryan-aguilar** [comment]
This change should be included in the upstream collector version `v0.64.0` and the ADOT Collector version `v0.24.0`

**Comment by lorelei-rupp-imprivata** [comment]
@bryan-aguilar so I just rolled this out but im not seeing this actually work
I put this in my configmap, added the log_retention item
```
apiVersion: v1
data:
  collector.yaml: |
    exporters:
      awsemf:
        dimension_rollup_option: NoDimensionRollup
        log_group_name: /aws/containerinsights/{ClusterName}/performance
        log_retention: 7
        log_stream_name: '{NodeName}'
......

I even deleted the existing log group, and it recreates it with "No Expiration"

Is there something else I am missing to get this to work?
```
